# Swap Ctrl-b with Ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Rebind keys to split windows
bind \ split-window -h
bind - split-window -v

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Shift+hjkl pane resizing
unbind Left
unbind Up
unbind Down
unbind Right
bind H resize-pane -L 5
bind J resize-pane -U 5
bind K resize-pane -D 5
bind L resize-pane -R 5

## Carrot keys for horizontal pane swapping
# Ctrl+jk for pane swapping
unbind {
unbind }
#bind , swap-pane -U
bind C-k swap-pane -U
#bind . swap-pane -D
bind C-j swap-pane -D
