#
# plugins.conf -- weechat v0.4.3
#

[var]
fifo.fifo = "on"
guile.check_license = "on"
lua.check_license = "on"
perl.check_license = "on"
perl.thinklight_blink.blink_highlight = "on"
perl.thinklight_blink.blink_pv = "on"
python.bandwidth.device = "eth0"
python.bandwidth.format = "%N(↓%DV%DU/s ↑%UV%UU/s)"
python.bandwidth.refresh_rate = "5"
python.bandwidth.separator = " "
python.check_license = "on"
ruby.check_license = "on"
tcl.check_license = "on"

[desc]
python.bandwidth.device = "Network interface(s) to monitor, in order, separated by ';'"
python.bandwidth.format = "Output formatting: %N = network interface, %DV = downstream value, %DU = downstream units (K or M), %UV = upstream value, %UU = upstream units (K or M).  Note: default setting uses UTF-8"
python.bandwidth.refresh_rate = "Refresh rate in seconds"
python.bandwidth.separator = "String displayed between output for multiple devices"
