function have_binary(){return have_nplastpass()||have_native_messaging()}function have_binary_function(a){return have_nplastpass()&&"function"==typeof g_nplastpass[a]?!0:have_native_messaging()&&lp_in_array(a,g_native_messaging_functions)?!0:!1}
function call_binary_function(){if(0<arguments.length){for(var a=arguments[0],b=[],c=null,d=1;d<arguments.length;d++)d==arguments.length-1&&"function"==typeof arguments[d]?c=arguments[d]:b[b.length]=arguments[d];if(have_nplastpass()&&"function"==typeof g_nplastpass[a]){var e;0==b.length?e=g_nplastpass[a]():1==b.length?e=g_nplastpass[a](b[0]):2==b.length?e=g_nplastpass[a](b[0],b[1]):3==b.length?e=g_nplastpass[a](b[0],b[1],b[2]):4==b.length?e=g_nplastpass[a](b[0],b[1],b[2],b[3]):5==b.length?e=g_nplastpass[a](b[0],
b[1],b[2],b[3],b[4]):6==b.length?e=g_nplastpass[a](b[0],b[1],b[2],b[3],b[4],b[5]):lplog("too many arguments passed to call_binary_function, funcname="+a+", argslen="+b.length);c&&c(e)}else if(have_native_messaging()&&lp_in_array(a,g_native_messaging_functions)){e={cmd:a,argcount:b.length};for(d=0;d<b.length;d++)e["arg"+d]=b[d];var f;"get_chrome_passwords"==a&&(f=c,c=function(a){f(JSON.parse(a))});native_messaging_send_message(e,c)}}}
function call_binary_function_if(){if(0<arguments.length)if(have_binary_function(arguments[0]))call_binary_function.apply(this,arguments);else if(1<arguments.length&&"function"==typeof arguments[arguments.length-1])arguments[arguments.length-1](!1)}var g_native_messaging=null,g_native_messaging_loaded=!1,g_native_messaging_functions=[],g_native_messaging_version=gs("Unknown"),g_native_messaging_build_date=gs("Unknown"),g_native_messaging_build_time=gs("Unknown");
function connect_native_messaging(){try{"undefined"==typeof chrome||("undefined"==typeof chrome.extension||"undefined"==typeof chrome.extension.connectNative)||(g_native_messaging=chrome.extension.connectNative("com.lastpass.nplastpass"),g_native_messaging.onMessage.addListener(native_messaging_message),g_native_messaging.onDisconnect.addListener(function(){g_native_messaging_loaded=!1;lplog("native messaging host disconnected");"undefined"!=typeof chrome.extension.lastError&&"undefined"!=typeof chrome.extension.lastError.message&&
lplog("last error: "+chrome.extension.lastError.message)}),native_messaging_send_message({cmd:"get_function_names",argcount:0},function(a){a&&(g_native_messaging_functions=a.split(","),g_native_messaging_loaded=!0,localStorage.setItem("hadNativeMessaging","1"),setup_wlan_variables(),setup_is_chrome_portable(),!have_nplastpass()&&g_onload_started&&onLoad(!0))}),native_messaging_send_message({cmd:"get_version",argcount:0},function(a){0>=CompareLastPassVersions(a,"3.0.15")?(g_native_messaging_loaded=
!1,g_native_messaging.disconnect(),lplog("blocked old native messaging host version "+a)):g_native_messaging_version=a}),native_messaging_send_message({cmd:"get_build_date",argcount:0},function(a){g_native_messaging_build_date=a}),native_messaging_send_message({cmd:"get_build_time",argcount:0},function(a){g_native_messaging_build_time=a}))}catch(a){}}var g_native_messaging_parts=[];
function native_messaging_message(a){if("undefined"!=typeof a.id){lpdbg("nativemessaging","got message, id="+a.id);var b=!1;if("undefined"!=typeof a.retval)b=!0;else if("undefined"!=typeof a.parts&&"undefined"!=typeof a.part&&"undefined"!=typeof a.retvalpart){if("undefined"==typeof g_native_messaging_parts[a.id]){g_native_messaging_parts[a.id]=[];for(var c=0;c<a.parts;c++)g_native_messaging_parts[a.id][c]=null}g_native_messaging_parts[a.id][a.part]=a.retvalpart;b=!0;for(c=0;c<a.parts;c++)if(null==
g_native_messaging_parts[a.id][c]){b=!1;break}if(b){a.retval="";for(c=0;c<a.parts;c++)a.retval+=g_native_messaging_parts[a.id][c];g_native_messaging_parts[a.id]=null}}b&&"function"==typeof g_native_messaging_callbacks[a.id]&&(b=g_native_messaging_callbacks[a.id],g_native_messaging_callbacks[a.id]=null,b(a.retval))}else if("undefined"!=typeof a.cmd)switch(lpdbg("nativemessaging","got message, cmd="+a.cmd),a.cmd){case "namedpipeobserverfunction":namedpipeobserverfunction(a.arg0,a.arg1,a.arg2);break;
case "basicauth_save":basicauth_save(a.arg0,a.arg1,a.arg2,a.arg3);break;case "basicauth_found":basicauth_found(a.arg0,a.arg1,a.arg2)}}function have_native_messaging(){return g_native_messaging_loaded}var g_native_messaging_callbacks={};
function native_messaging_send_message(a,b){try{var c=(new Date).getTime()+"_"+Math.floor(100*Math.random());lpdbg("nativemessaging","sending message, cmd="+("undefined"!=typeof a.cmd?a.cmd:"undefined")+", id="+c);g_native_messaging_callbacks[c]=b;a.id=c;g_native_messaging.postMessage(a)}catch(d){}}
function test_native_messaging(a){try{if(!g_ischrome||"undefined"==typeof chrome||"undefined"==typeof chrome.permissions||"undefined"==typeof chrome.permissions.contains)g_do_native_messaging=!1;else{var b=navigator.userAgent.match(/Chrome\/(\d+)/);b&&29>parseInt(b[1])?g_do_native_messaging=!1:!g_is_win&&!g_is_mac&&!g_is_linux?g_do_native_messaging=!1:chrome.permissions.contains({permissions:["nativeMessaging"]},a)}}catch(c){g_do_native_messaging=!1}}
function request_native_messaging(a){getBG().lpPutGblPref("native_messaging_asked","1");a?openURL(getchromeurl("native_messaging.html?hidenever=1")):chrome.permissions.request({permissions:["nativeMessaging"]},function(a){a&&alert(gs("Please restart your browser to finish enabling native messaging."))})}function native_messaging_never_ask_again(){getBG().lpPutGblPref("native_messaging_never_ask_again","1");getBG().lpWriteAllPrefs();getBG().closecurrenttab("native_messaging.html")}
var g_ask_native_messaging_from_button=!1;function open_native_messaging_html_if(){g_open_native_messaging_html&&!have_nplastpass()&&"1"!=lpGetPref("native_messaging_never_ask_again","0")&&lpGetPref("native_messaging_asked","0")}function install_binary(a,b){g_do_native_messaging&&!a&&!g_have_native_messaging_permission&&supports_native_messaging()?request_native_messaging(b):openURL(base_url+"installer/")}var g_debug_nplastpass=!0;
function debug_nplastpass(a){g_debug_nplastpass&&lpdbg("nplastpass",a)}var g_nplastpass_loaded=!1;
function have_nplastpass(a){debug_nplastpass("checking for binary component");try{g_nplastpass&&(g_nplastpass_loaded&&"undefined"==typeof g_nplastpass.alert)&&(debug_nplastpass("binary component loaded but alert function not found, resetting"),g_nplastpass=null)}catch(b){debug_nplastpass("caught exception while resetting binary component: "+b.message)}if(!g_nplastpass){debug_nplastpass("attempting to setup binary component");for(var c=0;c<(g_issafari?2:1);c++)try{if(0==c){if(debug_nplastpass("setting binary component global"),
g_nplastpass=document.getElementById("nplastpass"),!g_nplastpass&&g_isopera&&allow_nplastpass()){var d=document.createElement("embed");d.setAttribute("id","nplastpass");d.setAttribute("type","application/x-vnd-lastpass");document.body.appendChild(d);g_nplastpass=d}}else if(g_issafari)for(var e=0;e<safari.extension.bars.length;e++)if("LPMenu"==safari.extension.bars[e].identifier){var f=safari.extension.bars[e].contentWindow.document;f.getElementById("nplastpass")&&f.body.removeChild(f.getElementById("nplastpass"));
d=f.createElement("embed");d.setAttribute("id","nplastpass");d.setAttribute("type","application/x-vnd-lastpass");d.setAttribute("style","visibility: hidden;");f.body.appendChild(d);g_nplastpass=d;break}debug_nplastpass("type of alert is "+typeof g_nplastpass.alert);debug_nplastpass("checking for chrome portable");g_nplastpass.is_chrome_portable();debug_nplastpass("checking for wlan stuff");setup_wlan_variables();setup_is_chrome_portable();debug_nplastpass("checking for alert function");(g_nplastpass_loaded=
"undefined"!=typeof g_nplastpass.alert)?debug_nplastpass("binary component is loaded"):debug_nplastpass("binary component failed to load");break}catch(g){debug_nplastpass("caught exception while setting up binary component: "+g.message),g_nplastpass=null}}g_debug_nplastpass=!1;try{return"undefined"!=typeof g_nplastpass.alert&&(a||-1==navigator.userAgent.indexOf("Chrome/4.1.249.1042"))}catch(h){return!1}}
function get_nplastpass_version(){return have_nplastpass()&&"function"==typeof g_nplastpass.get_version?g_nplastpass.get_version():gs("Unknown")}function get_nplastpass_build_date_time(){return have_nplastpass()&&"function"==typeof g_nplastpass.get_build_date&&"function"==typeof g_nplastpass.get_build_time?g_nplastpass.get_build_date()+" "+g_nplastpass.get_build_time():gs("Unknown")};
