var do_bgiconinput=!0;
function popupfill_create_iframe(a,b,d,c,e,f,g,h){if(do_experimental_popupfill&&a){b=parseInt(b)+"px";d=parseInt(d)+"px";var j=a.body;if(j){a=a.createElement("iframe");a.id=LPMAGICIFRAME+c;a.name=LPMAGICIFRAME+c;g_fixed_iframe_position?h=!0:"undefined"==typeof h&&(h=!1);h&&(g_fixed_shuffled_once=!1);a.src=g_isie?"https://0.lastpass.com/#framesrc=LPMAGIC":urlprefix+"popupfilltab.html";0>parseInt(b)&&(b="0px");0>parseInt(d)&&(d="0px");dotrans?(g_frame_css_str=h?"display:block; position:fixed !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+
" !important; border-style:none !important;":"display:block; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:none !important;","undefined"!=typeof g_isie&&g_isie&&(g_frame_css_str+="background-color:transparent !important;background-image:none !important;")):g_frame_css_str=h?"display:block; position:fixed !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5);":
"display:block; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5);";a.style.cssText=g_frame_css_str;try{if(framesetarr=document.getElementsByTagName("frameset"),
0==framesetarr.length)j.appendChild(a);else{h=!1;for(j=0;j<framesetarr.length;j++)for(var k=0;k<framesetarr[j].children.length;k++)if("FRAME"==framesetarr[j].children[k].tagName&&(cf=framesetarr[j].children[k].contentWindow.document,null!=cf.getElementById(c)?(h=!0,toappendTo=cf.getElementById(c)):null!=cf.getElementsByName(c)&&(h=!0,toappendTo=cf.getElementsByName(c)[0])),h){toappendTo.parentNode.appendChild(a);break}}}catch(l){verbose_log("append failed! "+l);return}a.width=parseInt(f)+"px";a.height=
g_isie?"38px":"26px";"undefined"!=typeof e&&0<e&&(a.height=24*e+23+"px");a.height=0<parseInt(g)?parseInt(g)+"px":parseInt(a.height)+"px";c=parseInt(a.width)+"px";e=parseInt(a.height)+"px";a.style.cssText=g_frame_css_str+("width: "+c+" !important; height: "+e+" !important; top:"+d+" !important; left:"+b+" !important; ")}}}
function weasel(a){g_ctr_weasel++;if(do_experimental_popupfill){if("undefined"==typeof a||!1==a||!0==a||5>a)a=200;g_weaseled=!0;popupfill_resize();g_weasel_id=setTimeout(function(){weasel(a)},a)}}function issaveall(a){a=a.elements;for(var b=0,d=0,c=0,e=0;e<a.length;e++){var f=a[e].type;"password"==f?d++:"text"==f||"tel"==f||"email"==f?b++:"textarea"==f&&c++}return 1==b&&1==d&&0==c?!1:!0}var POPUP_FIELD_OFFSET=-4;
function calculate_iframe_pos(a,b,d,c){if(!do_experimental_popupfill)return null;"undefined"==typeof c&&(c=!1);if(!a||null==b)return null;var e=b.style.left,f=b.style.top;if(g_double_password_hack||g_double_secret_password_hack||0>parseInt(e)||0>parseInt(f)){var g=a.getElementById(LPMAGICIFRAME+LP_pickFieldName(a,b));if(null!=g&&(g=LP_getAbsolutePos(a,g)))return f=parseInt(g.top),e=parseInt(g.left),isNaN(f)||isNaN(e)?null:{posx:e+"px",posy:f+"px"}}LP_pickFieldName(a,b);if(null!=b){g=LP_getAbsolutePos(a,
b);null!=g&&(e=parseInt(g.left)+POPUP_FIELD_OFFSET+"px",f=parseInt(g.top)+parseInt(g.height)+"px",g_do_icon_number_hint&&(f=parseInt(g.top)+parseInt(g.height)+4+"px"));if(null==d||0==d||""==d)g=LP_getElementByIdOrName(a,LPMAGICIFRAME+LP_pickFieldName(a,b)),d=null!=g?(d=LP_getAbsolutePos(a,g))?d.width:0:0;if(!c){c=LP_getWindowWidth(window);if(!c)return{posx:0,posy:0};parseInt(d)+parseInt(e)>c&&(e=c-parseInt(d)-20+"px")}}if(""==e||"auto"==e||""==f||"auto"==f)return null;e=parseInt(e);f=parseInt(f);
return"NaN"==e||"NaN"==f?null:{posx:e+"px",posy:f+"px"}}function verbose_log(a){verbose&&console_log(a)}function is_watermark(){return!1}function checkAskGenerate(){}function sendKey(a,b){try{return keyName="DOM_VK_"+a.toUpperCase(),send_simulated_key(b,0,KeyEvent[keyName],!1)}catch(d){lpdbg("error",d)}return null}
function send_simulated_key(a,b,d,c){if(void 0===a||void 0===a.ownerDocument)return lpdbg("error","No key target!"),!1;b=a.ownerDocument.createEvent("KeyboardEvent");b.initKeyboardEvent("keydown",!0,!0,document.defaultView,!1,!1,c,!1,d,d);var e=a.dispatchEvent(b);b=a.ownerDocument.createEvent("KeyboardEvent");b.initKeyboardEvent("keyup",!0,!0,null,!1,!1,c,!1,d,d);a.dispatchEvent(b);return e}
if("undefined"==typeof KeyEvent)var KeyEvent={DOM_VK_CANCEL:3,DOM_VK_HELP:6,DOM_VK_BACK_SPACE:8,DOM_VK_TAB:9,DOM_VK_CLEAR:12,DOM_VK_RETURN:13,DOM_VK_ENTER:14,DOM_VK_SHIFT:16,DOM_VK_CONTROL:17,DOM_VK_ALT:18,DOM_VK_PAUSE:19,DOM_VK_CAPS_LOCK:20,DOM_VK_ESCAPE:27,DOM_VK_SPACE:32,DOM_VK_PAGE_UP:33,DOM_VK_PAGE_DOWN:34,DOM_VK_END:35,DOM_VK_HOME:36,DOM_VK_LEFT:37,DOM_VK_UP:38,DOM_VK_RIGHT:39,DOM_VK_DOWN:40,DOM_VK_PRINTSCREEN:44,DOM_VK_INSERT:45,DOM_VK_DELETE:46,DOM_VK_0:48,DOM_VK_1:49,DOM_VK_2:50,DOM_VK_3:51,
DOM_VK_4:52,DOM_VK_5:53,DOM_VK_6:54,DOM_VK_7:55,DOM_VK_8:56,DOM_VK_9:57,DOM_VK_SEMICOLON:59,DOM_VK_EQUALS:61,DOM_VK_A:65,DOM_VK_B:66,DOM_VK_C:67,DOM_VK_D:68,DOM_VK_E:69,DOM_VK_F:70,DOM_VK_G:71,DOM_VK_H:72,DOM_VK_I:73,DOM_VK_J:74,DOM_VK_K:75,DOM_VK_L:76,DOM_VK_M:77,DOM_VK_N:78,DOM_VK_O:79,DOM_VK_P:80,DOM_VK_Q:81,DOM_VK_R:82,DOM_VK_S:83,DOM_VK_T:84,DOM_VK_U:85,DOM_VK_V:86,DOM_VK_W:87,DOM_VK_X:88,DOM_VK_Y:89,DOM_VK_Z:90,DOM_VK_WIN:91,DOM_VK_CONTEXT_MENU:93,DOM_VK_NUMPAD0:96,DOM_VK_NUMPAD1:97,DOM_VK_NUMPAD2:98,
DOM_VK_NUMPAD3:99,DOM_VK_NUMPAD4:100,DOM_VK_NUMPAD5:101,DOM_VK_NUMPAD6:102,DOM_VK_NUMPAD7:103,DOM_VK_NUMPAD8:104,DOM_VK_NUMPAD9:105,DOM_VK_MULTIPLY:106,DOM_VK_ADD:107,DOM_VK_SEPARATOR:108,DOM_VK_SUBTRACT:109,DOM_VK_DECIMAL:110,DOM_VK_DIVIDE:111,DOM_VK_F1:112,DOM_VK_F2:113,DOM_VK_F3:114,DOM_VK_F4:115,DOM_VK_F5:116,DOM_VK_F6:117,DOM_VK_F7:118,DOM_VK_F8:119,DOM_VK_F9:120,DOM_VK_F10:121,DOM_VK_F11:122,DOM_VK_F12:123,DOM_VK_F13:124,DOM_VK_F14:125,DOM_VK_F15:126,DOM_VK_F16:127,DOM_VK_F17:128,DOM_VK_F18:129,
DOM_VK_F19:130,DOM_VK_F20:131,DOM_VK_F21:132,DOM_VK_F22:133,DOM_VK_F23:134,DOM_VK_F24:135,DOM_VK_NUM_LOCK:144,DOM_VK_SCROLL_LOCK:145,DOM_VK_COMMA:188,DOM_VK_PERIOD:190,DOM_VK_SLASH:191,DOM_VK_BACK_QUOTE:192,DOM_VK_OPEN_BRACKET:219,DOM_VK_BACK_SLASH:220,DOM_VK_CLOSE_BRACKET:221,DOM_VK_QUOTE:222,DOM_VK_META:224};var g_formmutations=0;
function checkShouldRecheck(){if(!(20<g_formmutations)&&do_experimental_popupfill&&(verbose_log("entered checkShouldRecheck()"),0<=g_input_cnt&&0<=g_form_cnt)){var a=countInputs(document),b=countFormEquivalents(document),d=computeFingerprint(document);verbose_log("checkShouldRecheck() : # inputs was "+g_input_cnt+", now "+a+" #forms was "+g_form_cnt+" now "+b+", fingerprint was "+g_input_fingerprint+" now "+d);if(g_input_cnt!=a||g_form_cnt!=b||g_input_fingerprint!=d)g_formmutations++,formcachereset(document),
fieldcachereset(document),g_isie?(setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},200),setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},1E3)):setTimeout(function(){g_ctr_recheck++;evalScriptsInFrame(window,document,!0)},200),g_input_cnt=a,g_form_cnt=b,g_input_fingerprint=d}}function is_watermark_password(){return!1}
function LP_addEventHandler(a,b,d){try{return null==a||null==b||null==d||0>=b.length?null:"undefined"!=typeof a.addEventListener?a.addEventListener(b,d,!1):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,d):null}catch(c){return verbose_log("LP_addEventHandler failed, "+c.message),null}}
function LP_stopEventPropagation(a){try{"undefined"!=typeof a.preventDefault?a.preventDefault():typeof window.event&&(window.event.returnValue=!1),"undefined"!=typeof a.stopPropagation?a.stopPropagation():typeof window.event&&(window.event.cancelBubble=!0)}catch(b){verbose_log("LP_stopEventPropagation failed, "+b.message)}}
function LP_getEventTarget(a){a=a?a:window.event;if((a="undefined"!=typeof a.target?a.target:a.srcElement)&&"undefined"!=typeof a.nodeType&&3==a.nodeType)a=a.parentNode;return a}
function createpopuptoplevel_handler(a){var b=LP_derive_doc(),d=parseInt(a.from_iframe.posx),c=parseInt(a.from_iframe.posy),e=a.from_iframe.id,f=a.from_iframe.rows,g=a.from_iframe.width,h=a.from_iframe.framename;a=a.from_iframe.framesrc;if(!is_your_popup_showing(b)){var h=find_iframe_pos(b,h,a),j=a=0;h?(a=parseInt(h.left)+d+"px",j=parseInt(h.top)+c+"px",g_toplevel_initial_abs_x=a,g_toplevel_initial_abs_y=j):j=a="10px";popupfill_create_iframe(b,a,j,e,f,g,"90px",!0);g_popupfill_iframe_width_save=g}}
var g_toplevel_initial_abs_x=null,g_toplevel_initial_abs_y=null;function popupfillresize_handler(a){g_minwidth_override=parseInt(a.width);g_minheight_override=parseInt(a.height);g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&!LP_inIframe(window)&&toplevel_iframe_state_get()&&relocate_popupfill_iframes(document)}
function find_iframe_pos(a,b,d){if(!a)return null;var c;try{var e=a.getElementsByTagName("IFRAME");if(!b&&1==e.length)return LP_getAbsolutePos(a,e[0],!0);var f=[];for(c=0;c<e.length&&50>c;c++)f[c]=e[c];for(c=0;c<f.length;c++)if(f[c].name&&""!=b&&f[c].name==b||f[c].src&&""!=d&&f[c].src==d)return LP_getAbsolutePos(a,f[c],!0)}catch(g){}return null};
