var LPCFG={do_popup_actions:!0,popup_show_sitename_suffix:!0,popup_show_menu_expand_visual_cue:!0,g_do_icon_number_hint:!0,g_creditcard_profile_annotate:!0,g_visual_cue_on_hover:!0,RETRY_TIMEOUT_QUANTUM:30,__FINAL:0},LPIFRAMEVARS={g_genpws:[],g_myprefs:{},g_should_set_prefs:!0,g_sites:null,g_formfills:null,g_favicons:null,_FINAL:0},LPpop={create_popup_obj:function(a,d){function j(a){var b=0,c;for(c in a)b++;return b}if(do_experimental_popupfill){var c="undefined"!=typeof g_isfirefox&&g_isfirefox?
"html:":"",b=null,f=null,l=null,n=null,n=a.createElement(c+"div");n.style.display="block";n.style.border="0";if(!n)return null;var k=null,g=null,k=f=null,h,s,q,e,p=0,l=0;LPCFG.popup_show_menu_expand_visual_cue&&(l=24);q="undefined"!=typeof measureText?measureText:LP_measureText;var t={};"undefined"!=typeof d.favicons&&(t=LPJSON.parse(d.favicons));k=a.createElement(c+"div");if(!k)return null;k.setAttribute("id","popupcontainer");n.appendChild(k);g=a.createElement(c+"table");if(!g)return null;g.setAttribute("id",
"lptabpopup");k.appendChild(g);f=a.createElement(c+"div");if(!f)return null;f.setAttribute("id","popupcontainerff");n.appendChild(f);k=a.createElement(c+"table");if(!k)return null;k.setAttribute("id","lptabpopupformfills");k.style.display="none";f.appendChild(k);if("undefined"==typeof d.sites)s=0;else for(e in h=LPpop.getAutoFillArray(a,LPJSON.parse(d.sites),!0),s=j(h),h)if(h.hasOwnProperty(e)&&null!=h[e]&&null!=h[e].useusername){var m=h[e].useusername;0>=m.length&&(m=h[e].name);var r=m,b=a.createElement(c+
"tr");if(!b)return null;b.setAttribute("id","trpopuprow"+lp_ofa(e));b.setAttribute("aid",h[e].aid);b.setAttribute("sitename",h[e].name);b.setAttribute("username",h[e].useusername);b.className="popuprow";g.appendChild(b);f=a.createElement(c+"td");if(!f)return null;f.setAttribute("id","tdpopuprow"+lp_ofa(e));f.setAttribute("aid",lp_ofa(h[e].aid));b.appendChild(f);"undefined"!=typeof t[h[e].aid]&&(b=LPpop.gen_image_frag(a,LPpop.lookup_favicon(h[e].aid)))&&f.appendChild(b);b=a.createElement(c+"span");
if(!b)return null;b.setAttribute("id","spanpopuprow"+lp_ofa(e));b.className="popcell shortenstr";LP_elt_set_text(b,m);f.appendChild(b);LPCFG.popup_show_menu_expand_visual_cue&&(b=LPpop.visual_cue_frag(a,"expand",e))&&f.appendChild(b);LPCFG.popup_show_sitename_suffix&&(b=LPpop.subscript_name_frag(a,h[e].name))&&f.appendChild(b);f=q(a,lp_of(r,a),null,"font-size: 14px;font-family: Helvetica,Arial,sans-serif;font-weight:bold;");f.width+20+l>p&&(p=f.width+20+l)}if("undefined"==typeof d.formfills)q=0;else{g=
LPJSON.parse(d.formfills);q=j(g);for(h=0;1>=h;h++)for(e in g)if(g.hasOwnProperty(e)&&null!=g[e]&&null!=g[e].decprofilename&&null!=g[e].profiletype&&parseInt(g[e].profiletype)===h){b=a.createElement(c+"tr");if(!b)return null;b.setAttribute("id","trpopupffrow"+lp_ofa(e));b.setAttribute("ffid",g[e].ffid);b.setAttribute("profilename",g[e].decprofilename);b.setAttribute("formtype",h);""!=g[e].ccnum&&0==g[e].profiletype&&b.setAttribute("hascc","1");b.className="popuprow";k.appendChild(b);f=a.createElement(c+
"td");if(!f)return null;f.setAttribute("id","tdpopupffrow"+lp_ofa(e));f.setAttribute("ffid",g[e].ffid);b.appendChild(f);"undefined"!=typeof t[g[e].ffid]&&(b=LPpop.gen_image_frag(a,LPpop.lookup_favicon(g[e].ffid)))&&f.appendChild(b);r=lp_of(g[e].decprofilename,a);b=a.createElement(c+"span");b.className="popcell shortenstr";b.setAttribute("id","spanpopupffrow"+lp_ofa(e));LP_elt_set_text(b,lp_of(g[e].decprofilename,a));f.appendChild(b);LPCFG.g_creditcard_profile_annotate&&1==h&&(m=a.createElement(c+
"span"),m.className="cc",LP_elt_set_text(m,"("+lpgs("Credit Card")+")"),b.appendChild(m),r+=lpgs("Credit Card"));LPCFG.popup_show_menu_expand_visual_cue&&(b=LPpop.visual_cue_frag(a,"expandff",e))&&f.appendChild(b);f=measureText(a,r,null,"font-size: 14px;font-family: Helvetica,Arial,sans-serif;font-weight:bold;");f.width+20+l>p&&(p=f.width+20+l)}}if(LPCFG.do_popup_actions){if(0<q){b=a.createElement(c+"tr");if(!b)return null;b.className="tablerow_sep";k.appendChild(b);f=a.createElement(c+"td");if(!f)return null;
b.appendChild(f);l=a.createElement(c+"hr");if(!l)return null;f.appendChild(l)}}else if(0>=s&&0>=q)return null;300<p&&(p=300);g_popupfill_widest=p;return n}},visual_cue_frag:function(a,d,j){var c=null,b="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"";if(!d||!a)return null;if(LPCFG.popup_show_menu_expand_visual_cue){c=a.createElement(b+"span");if(!c)return null;c.setAttribute("id",d+lp_ofa(j));c.setAttribute("expander","true");c.className="expander";LPCFG.g_visual_cue_on_hover&&(c.style.display=
"none");if(a=LPpop.gen_image_frag(a,"arrow.png"))a.setAttribute("id",d+"img"+lp_ofa(j)),a.setAttribute("alt","+"),c.appendChild(a)}return c},subscript_name_frag:function(a,d){var j=null;if(!a)return null;var c="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"";d&&0<d.length&&(j=a.createElement(c+"p"),j.className="subtext",LP_elt_set_text(j,lp_of(d,a)));return j},gen_image_frag:function(a,d){if(!a)return null;var j="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"",c=null;if(g_isfirefox){c=
a.createElement("image");if(!c)return null;c.setAttribute("src",d);c.style.padding="2px"}else{c=a.createElement(j+"img");if(!c)return null;c.setAttribute("src",d);c.style.padding="2px";c.setAttribute("alt","")}return c},set_icon_hint_from_data:function(a,d){function j(a){var b=0,c;for(c in a)b++;return b}if(LPCFG.g_do_icon_number_hint){var c,b;"undefined"==typeof d.sites?c=0:(c=LPpop.getAutoFillArray(a,LPJSON.parse(d.sites),!0),c=j(c));"undefined"==typeof d.formfills?b=0:(b=LPJSON.parse(d.formfills),
b=j(b));g_icon_numbers.sites=c;g_icon_numbers.formfills=b}},getAutoFillArray:function(a,d,j){var c=[];a=punycode.URLToASCII(a.location.href);lpcanonizeUrl(a);for(var b in d)if(!d[b].genpw||j)c[b]=d[b];return c},lookup_username:function(a){var d;if(LPIFRAMEVARS&&LPIFRAMEVARS.g_sites&&null!==a)for(d in LPIFRAMEVARS.g_sites)if(LPIFRAMEVARS.g_sites[d]&&LPIFRAMEVARS.g_sites[d].aid==a){a=LPIFRAMEVARS.g_sites[d];if(a.useusername)return a.useusername;if(a.unencryptedUsername)return a.unencryptedUsername;
break}return""},lookup_sitename:function(a){var d;if(LPIFRAMEVARS&&LPIFRAMEVARS.g_sites&&null!==a)for(d in LPIFRAMEVARS.g_sites)if(LPIFRAMEVARS.g_sites[d]&&LPIFRAMEVARS.g_sites[d].aid==a){a=LPIFRAMEVARS.g_sites[d];if(a.sitename)return a.sitename;if(a.name)return a.name;break}return""},lookup_profile:function(a){var d;if(LPIFRAMEVARS&&LPIFRAMEVARS.g_formfills&&null!==a)for(d in LPIFRAMEVARS.g_formfills)if(LPIFRAMEVARS.g_formfills[d]&&LPIFRAMEVARS.g_formfills[d].ffid==a){a=LPIFRAMEVARS.g_formfills[d];
if(a.decprofilename)return a.decprofilename;if(a.decprofilename)return a.profilename;break}return""},lookup_favicon:function(a){if(LPIFRAMEVARS&&LPIFRAMEVARS.g_favicons&&null!==a)return(a=LPIFRAMEVARS.g_favicons[a])?a:null},__FINAL__:0};
