function hasNeverAutologin(b,a){var f=lpcanonizeUrl(b);if(g_neverurls.onlyautologins&&0<g_neverurls.onlyautologins.length){for(var e=!1,c=0;g_neverurls.onlyautologins&&c<g_neverurls.onlyautologins.length;c++){var d=g_neverurls.onlyautologins[c];if(d==a||d==f){e=!0;break}}if(!e)return!0}for(c=0;g_neverurls.neverautologins&&c<g_neverurls.neverautologins.length;c++)if(d=g_neverurls.neverautologins[c],d==a||d==f)return!0;return!1}
function hasNeverGenerate(b,a){var f=lpcanonizeUrl(b);if(g_neverurls.onlygenerates&&0<g_neverurls.onlygenerates.length){for(var e=!1,c=0;g_neverurls.onlygenerates&&c<g_neverurls.onlygenerates.length;c++){var d=g_neverurls.onlygenerates[c];if(d==a||d==f){e=!0;break}}if(!e)return!0}for(c=0;g_neverurls.nevergenerates&&c<g_neverurls.nevergenerates.length;c++)if(d=g_neverurls.nevergenerates[c],d==a||d==f)return!0;return!1}
function hasNeverFormFill(b,a){var f=lpcanonizeUrl(b);if(g_neverurls.onlyformfills&&0<g_neverurls.onlyformfills.length){for(var e=!1,c=0;g_neverurls.onlyformfills&&c<g_neverurls.onlyformfills.length;c++){var d=g_neverurls.onlyformfills[c];if(d==a||d==f){e=!0;break}}if(!e)return!0}for(c=0;g_neverurls.neverformfills&&c<g_neverurls.neverformfills.length;c++)if(d=g_neverurls.neverformfills[c],d==a||d==f)return!0;return!1}var g_accessibility_enabled=-1;
function handleFill(b,a){var f=!1;if(lploggedin&&null==grid_getdata("active")||skiplogin())if("autofillaid"==a.cmd||"autologinaid"==a.cmd){var e=a.aid;g_last_launch[e]=(new Date).getTime();if("undefined"!=typeof g_sites[e]){var f="autologinaid"==a.cmd,c=!0,d=g_sites[e];a.no_manualfill_on_saveall&&d.save_all&&(c=!1);a.from_iframe&&!d.save_all&&(c=!0);d=a.from_iframe?!0:!1;fill(b,g_sites[e],null,f,!f,"all",!0,!1,c,null,null,d)}}else if(!("undefined"==typeof a||!a||"undefined"==typeof a.url)){var c=
a.url,g=lp_gettld_url(c);if(!lp_url_is_lastpass(c)){if("undefined"==typeof g_launches[b]||!g_launches[b])null!=g_pending_launch&&(g_launches[b]=g_pending_launch);if("undefined"!=typeof g_launches[b]&&g_launches[b]&&(e=g_launches[b],check_ident_aid(e)&&compare_tlds(g,lp_gettld_url(g_sites[e].url)))){if("undefined"!=typeof a.numpass&&0<a.numpass||""==g_sites[e].password)g_launches[b]=null;"undefined"!=typeof g_sites[e]&&(is_guiless()?fill(b,g_sites[e],null,!1,!1,"all",!0,!1,!1,!1):(d=a.from_iframe?
!0:!1,fill(b,g_sites[e],null,!0,!1,a.docnum,!1,!0,null,null,null,d)),g_pending_launch=g_launches[b]=null)}var k=getsites(g),k=reorderOnURL(k,c,!0);hasNeverAutologin(c,g)&&(k=[]);e=0==a.force&&a.topurl!=c?lp_gettld_url(a.topurl):"";""!=e&&hasNeverAutologin(a.topurl,e)&&(k=[]);for(var l in k){try{if(islastpass&&g_ischrome&&1==k[l].basic_auth&&0>=g_accessibility_enabled&&0==lpGetPref("basicauthnever",0))if(g_is_mac&&have_binary_function("accessibility_enabled"))call_binary_function("accessibility_enabled",
function(a){g_accessibility_enabled=a?1:0;0==g_accessibility_enabled&&setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",needbinary:0,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to enable access for assistive devices.")})})},100)});else if((g_is_win||g_is_mac)&&!have_binary())g_accessibility_enabled=0,setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",
needbinary:1,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to install the binary version of LastPass for Chrome.")})})},100)}catch(j){}g=!1;e=k[l].aid;if(check_ident_aid(e)&&"undefined"!=typeof g_sites[e]){d=g_sites[e];d.never_autofill&&(g=!0);if(d.pwprotect||g_prompts.login_site_prompt)g=!0;if(!d.genpw&&!(0==d.fields.length&&""==d.username)){0==d.url.indexOf("https://")&&0!=c.indexOf("https://")&&(g=!0);0==parseInt(lpGetPref("automaticallyFill",1))&&0==parseInt(lpGetPref("highlightFields",
1))&&(g=!0);if(!g){if(e=!d.save_all)"undefined"==typeof g_fillfieldsmatches[c]&&(g_fillfieldsmatches[c]=[]),g_fillfieldsmatches[c][g_fillfieldsmatches[c].length]=d,g_fillfieldsmatchescurridx[c]=0;l=parseInt(lpGetPref("automaticallyFill",1));fill(b,d,a.docid,null,e,a.docnum,null,!0,null,l)}0!=lpGetPref("showFillNotificationBar",1)&&(get_selected_tab(null,function(){sendCS(b,{cmd:"showfillnotification",text:gs("LastPass has filled your login information into the form on this page."),sites:cache_usernames(k),
docnum:a.docnum})}),f=!0);break}}}!f&&0==lpGetPref("showNotificationsAfterClick",1)&&checkgenpwfillforms(b,c)}}}
function checkWeakAndDuplicate(b,a,f){if(g_showweakdupalerts&&qualifyForWeakCheck(getpasswordfromacct(b))&&(g_ischrome||g_issafari))!1==g_disablepwalerts&&("undefined"==typeof b.noalert||"1"!=b.noalert)&&getWeakAndDuplicateIds(g_username_hash,g_username,function(e){isDuplicateSite(e[0],b.aid)?(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:b.aid,name:b.name,username:getusernamefromacct(b),alerttype:"duplicate",tld:f,tabid:a},set_badge(g_notification_data,a),drawIconAtRotation(0)):
isWeakPassword(e[1],b.aid)&&(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:b.aid,name:b.name,username:getusernamefromacct(b),alerttype:"weak",tld:f,tabid:a},set_badge(g_notification_data,a),drawIconAtRotation(0))})}
function checkgenpwfillforms(b,a,f){var e=lp_gettld_url(a),c=1!=lpGetPref("showGenerateNotifications",1)||hasNeverGenerate(a,e),d=1!=lpGetPref("showFormFillNotifications",1)||hasNeverFormFill(a,e),g=[];if(do_experimental_popupfill){for(var k=0;k<g_formfills.length;k++)check_ident_ffid(g_formfills[k].ffid)&&(g[g.length]=g_formfills[k]);0==g.length&&(d=!0);a={cmd:"checkgenpwfillforms",nevergenerate:c,neverformfill:d,sites:cache_usernames(reorderOnURL(getsites(e),a,!0,!0)),formfills:LPJSON.stringify(g),
active:g_popupfill_last_active[b],activefieldid:g_popupfill_last_active_fieldid[b]};f||(a.ff=g_cachedffdat);sendCS(b,a,"all")}else{if(!d){for(k=0;k<g_formfills.length;k++)check_ident_ffid(g_formfills[k].ffid)&&(g[g.length]=g_formfills[k]);0==g.length&&(d=!0)}if(!c||!d)a={cmd:"checkgenpwfillforms",nevergenerate:c,neverformfill:d,sites:cache_usernames(reorderOnURL(getsites(e),a,!0,!0)),formfills:LPJSON.stringify(g)},f||(a.ff=g_cachedffdat),sendCS(b,a,"all")}}
function cache_usernames(b){for(var a in b)b[a].useusername=getusernamefromacct(b[a]);return LPJSON.stringify(b)}
function hasNeverSave(b,a){var f=lpcanonizeUrl(b);0<f.length&&"/"==f.charAt(f.length-1)&&(f=f.substring(0,f.length-1));if(g_neverurls.onlyaccounts&&0<g_neverurls.onlyaccounts.length){for(var e=!1,c=0;g_neverurls.onlyaccounts&&c<g_neverurls.onlyaccounts.length;c++){var d=g_neverurls.onlyaccounts[c];if(d==a||d==f){e=!0;break}}if(!e)return!0}for(c=0;g_neverurls.neveraccounts&&c<g_neverurls.neveraccounts.length;c++)if(d=g_neverurls.neveraccounts[c],d==a||d==f)return!0;return!1}
function handleNever(b,a){if("neverautofill"==a.cmd){var f=a.aid;if("undefined"==typeof g_sites[f])return;g_sites[f].never_autofill=!0;g_sites[f].autologin=!1;f="aid="+en(f);lpMakeRequest(base_url+"set_never_autofill.php",f,null,null)}else if("neverdomain"==a.cmd||"neverpage"==a.cmd){var e="neverdomain"==a.cmd?lp_gettld_url(a.url):lpcanonizeUrl(a.url),f="url="+en(AES.url2hex(e));"undefined"!=typeof a.fromsave&&a.fromsave?g_neverurls.neveraccounts.push(e):"undefined"!=typeof a.fromgenerate&&a.fromgenerate?
(f+="&type=1",g_neverurls.nevergenerates.push(e)):"undefined"!=typeof a.fromformfill&&a.fromformfill?(f+="&type=2",g_neverurls.neverformfills.push(e)):"undefined"!=typeof a.fromshowicons&&a.fromshowicons?(f+="&type=6",g_neverurls.nevershowicons.push(e)):(f+="&type=3",g_neverurls.neverautologins.push(e));lpMakeRequest(base_url+"add_never.php",f,null,null)}g_local_accts_version++;rewritelocalfile()}
function handleSave(b,a){if(b==g_pwchangetabid)console.error("Skipping save because driving a password change");else{var f=get_ff_translation("ff_currpass_regexp");if(!("undefined"==typeof SAVEALLFORMSUBMITS&&(!lploggedin||lp_url_is_lastpass(a.url,!0)))){for(var e=a.formdata.split("\n"),c=!1,d=!1,g=null,k="",l="",j=[],m=0;m<e.length;m++){var h=e[m],h=h.split("\t");if(!(4!=h.length&&5!=h.length)){var n=decodeURIComponent(h[2]),p=h[3];if((!c||!d)&&("text"==p||"email"==p||"tel"==p||"url"==p)&&n.length)k=
n,c=!0,!1==d&&"undefined"!=typeof SpecialSites[lpcanonizeUrl(a.url)]&&(d=!0);if("password"==p&&(j[j.length]=n,!d&&n.length&&(l=n,d=!0),null==g)){var n=decodeURIComponent(h[1]),q=RegExp(f,"i");if(n&&(n==a.current_pw_field_name||q.exec(n)))g=j.length-1}}}if(d){a.username=k;a.password=l;!c&&1<j.length&&(j[0]!=j[1]&&null==g)&&(a.username=j[0],a.password=j[1]);f=lp_gettld_url(a.url);a.tld=f;h=!1;d="";1<j.length&&j[j.length-1]==j[j.length-2]&&""!=j[j.length-1]?(h=!0,d=j[j.length-1]):1<j.length&&j[0]==j[1]&&
""!=j[0]?(h=!0,d=j[0]):1<j.length&&(j[0]!=j[1]&&""!=j[0]&&null!=g)&&(d=0==g&&2==j.length?j[1]:1==g&&2==j.length?j[0]:"");var t=h||null!=g&&d,g=[];if(t&&(g=getsites(f,!0),a.createacct=2==j.length||0<array_length(g),a.createacct)){for(var u=j="",r="",v="",m=0;m<e.length;m++)if(h=e[m],h=h.split("\t"),!(4!=h.length&&5!=h.length)){p=h[3];if(""==j&&("email"==p||"tel"==p||"text"==p||"url"==p)&&""!=h[1]&&""!=h[2])n=decodeURIComponent(h[1]),q=get_ff_translation("ff_username_regexp"),""!=q&&(q=RegExp(q,"i"),
q.exec(n)&&(j=n,u=decodeURIComponent(h[2])));if(""==r&&("email"==p||"tel"==p||"text"==p||"url"==p)&&""!=h[1]&&""!=h[2])n=decodeURIComponent(h[1]),p=get_ff_translation("ff_email_regexp"),""!=p&&(q=RegExp(p,"i"),q.exec(n)&&(r=n,v=decodeURIComponent(h[2])));if(""!=j&&""!=r)break}""==j&&(j=r,u=v);a.username_field=j;""!=u&&(a.username=u)}if(t&&0<array_length(g)){if(c="undefined"!=typeof g_didchangepw[SHA256(d+f)]&&g_didchangepw[SHA256(d+f)]>(new Date).getTime()-6E5,console.log("already processed pw "+
d+" is "+c),!c&&(g_notification_type="change",a.newpw=d,g_notification_data=a,sendTS({cmd:"notification",type:"change"}),0!=lpGetPref("showChangeNotificationBar",1))){var e=g,s;a.sitecount=array_length(e);if(1==array_length(e))for(m in e){a.singleaid=m;s=gs("LastPass detected a password change for user:")+" "+getusernamefromacct(g_sites[m]);break}else s=gs("LastPass detected a password change for domain:")+" "+f;sendCS(b,{cmd:"showchangenotification",text:s,notificationdata:a});g_persistent_notifications[b]=
{cmd:"showchangenotification",text:s,notificationdata:a}}}else if(!hasNeverSave(a.url,f)){var e=getsites(f),w;for(w in e)if(check_ident_aid(w)&&"undefined"!=typeof g_sites[w]&&(m=g_sites[w],s=getusernamefromacct(m),e=getpasswordfromacct(m),(!c||k==lpmdec_acct(m.username,!0,m,g_shares)||0==k.indexOf("****")||k==s)&&(l==lpmdec_acct(m.password,!0,m,g_shares)||l==e)||m.save_all&&isMatch(m,c,k,l)||k==lpmdec_acct(m.username,!0,m,g_shares)&&""==l))return;g_notification_type="save";g_notification_data=a;
"function"==typeof ManSubmitCallback?(c=[],c.postdata=g_notification_data.formdata,c.tld=f,ManSubmitCallback(c)):(0!=lpGetPref("showSaveSiteNotifications",0)&&sendTS({cmd:"notification",type:"save"}),0!=lpGetPref("showSaveNotificationBar",1)&&lpCheckAddSite(a.username,a.password,f)&&(sendCS(b,{cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),notificationdata:LPJSON.stringify(a)}),g_persistent_notifications[b]={cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),
notificationdata:LPJSON.stringify(a)}))}}}}}function lpCheckAddSite(b,a,f){var e=lp_get_gmt_timestamp(),c=[],d;for(d in g_rejectedaddsites){var g=g_rejectedaddsites[d];e>g.rejectedTime+600&&(c[c.length]=d)}for(d=c.length-1;0<=d;d--)g_rejectedaddsites.splice(c[d],1);for(d in g_rejectedaddsites)if(g=g_rejectedaddsites[d],g.username==b&&lpdec(g.encryptedPassword)==a&&compare_tlds(g.tld,f))return!1;return!0}var lastupdatefields="";
function handleUpdateFields(b,a){var f=a.aid,e=g_sites[f],c=issharedfolder(g_shares,e.group);if(checkreadonly(c,!0)){var d=[],g=[],k=updateAndEncryptData(a.formdata,d,g,e),l=SHA256(k);if(l!=lastupdatefields){lastupdatefields=l;update_username_from_fields_if(e,d);for(l=e.fields.length-1;0<=l;l--)!e.fields[l].otherfield&&"1"!=e.fields[l].otherlogin&&e.fields.splice(l,1);for(l=0;l<d.length;l++)e.fields[e.fields.length]=d[l];g_local_accts_version++;rewritelocalfile();f="data="+en(bin2hex(k))+"&ref="+
en(url2hex(a.url))+"&updatefields=1&aid="+en(f);f+=!1==c?"":"&sharedfolderid="+en(c.id);e.postdata=f;e.posturl=base_url+"gm_deliver.php";e.newvalues=g;updateFieldsFromSubmit(f,e)}}}
function handleAddUrid(b,a){var f=a.aid,e=g_sites[f],c=issharedfolder(g_shares,e.group);if(checkreadonly(c,!0)){for(var d=[],g=0;g<e.fields.length;g++)"1"==e.fields[g].otherlogin&&!lp_in_array(e.fields[g].urid,d)&&(d[d.length]=e.fields[g].urid);if(!(10<=d.length)){var k=[],d=[],l=updateAndEncryptData(a.formdata,k,d,e);update_username_from_fields_if(e,k);for(g=0;g<k.length;g++)k[g].otherlogin="1",k[g].url=url2hex(a.url),e.fields[e.fields.length]=k[g];g_local_accts_version++;rewritelocalfile();f="data="+
en(bin2hex(l))+"&ref="+en(url2hex(a.url))+"&addurid=1&aid="+en(f);f+=!1==c?"":"&sharedfolderid="+en(c.id);e.postdata=f;e.posturl=base_url+"gm_deliver.php";e.newvalues=d;updateFieldsFromSubmit(f,e)}}}
function update_username_from_fields_if(b,a){for(var f=0,e="",c=0;c<a.length;c++)if("text"==a[c].type||"email"==a[c].type||"tel"==a[c].type||"url"==a[c].type)if(e=a[c].value,2<=++f)break;if(1==f&&""!=e){for(c=f=0;c<b.fields.length;c++)if(!b.fields[c].otherfield&&("text"==b.fields[c].type||"email"==b.fields[c].type||"tel"==b.fields[c].type||"url"==b.fields[c].type)){f++;break}0==f&&(b.username=e,b.unencryptedUsername=lpdec_acct(crypto_btoa(b.username),b,g_shares))}}
function handleSaveAll(b,a){a.save_all=1;g_site_data=a;openURL(getchromeurl("site.html"))}
function isMatch(b,a,f,e){a=a?!1:!0;for(var c=!1,d=0;d<b.fields.length;d++)if(!("text"!=b.fields[d].type&&"password"!=b.fields[d].type&&"email"!=b.fields[d].type&&"tel"!=b.fields[d].type&&"url"!=b.fields[d].type)){var g=lpmdec_acct(b.fields[d].value,!0,b,g_shares);if(("text"==b.fields[d].type||"email"==b.fields[d].type||"tel"==b.fields[d].type||"url"==b.fields[d].type)&&f==g)a=!0;"password"==b.fields[d].type&&e==g&&(c=!0)}return a&&c?!0:!1}var g_reqindex=0;
function fill(b,a,f,e,c,d,g,k,l,j,m,h){verbose_log("tabid="+b+"\nacct="+a+"\ndocid="+f+"\nsubmit="+e+"\ndoconfirm="+c+"\ndocnum="+d+"\nallowforce="+g+"\nskip_pwprotect="+k+"\nmanualfill="+l+"\nautomaticallyFill="+j+"\nskip_basicauth="+m+"\nfrom_iframe="+h);if("undefined"==typeof j||null==j)j=1;l||(l=!1);!k&&(a.pwprotect||g_prompts.login_site_prompt)?(console_log("FILL : Showing Security Prompt"),security_prompt(function(){setTimeout(function(){fill(b,a,f,e,c,d,g,!0,l,null,null,h)},100)})):get_selected_tab(null,
function(n){if(!m&&j&&(g||1==a.basic_auth)&&gettabid(n)==b&&g_ischrome&&have_binary_function("fill_basicauth")){n=getusernamefromacct(a);var p=getpasswordfromacct(a);if(""!=n||""!=p){var q=check_autologin(e,a),t=lp_gettld_url(a.url),u=lp_gettld_url(g_basicauth_origurl);compare_tlds(t,u)&&(t=u);call_binary_function("fill_basicauth",n,p,g?!0:!1,t,q?!0:!1,function(h){h?g_basicauth_found=!1:fill(b,a,f,e,c,d,g,k,l,j,!0)});return}}is_guiless()&&(j=1);t=a.tld;n=a.fields;q=n.length;c=1==c?1:0;g=g?1:0;h=h?
1:0;p=null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?1:0;if(0!=q){for(q=t=0;q<n.length;q++)"password"==n[q].type&&t++;t=!a.save_all&&0==t;u=[];for(q=0;q<n.length;q++)if(a.save_all||!(1==c&&"password"!=n[q].type&&!g&&!t)){var r=n[q],v=r.value;if(!(""!=r.name&&"undefined"!=typeof u[r.name+v+r.type])){u[r.name+v+r.type]=1;var s=r.type;if(!("undefined"!=typeof a.captcha_id&&""!=a.captcha_id&&a.captcha_id==r.name&&"text"==s)){if("text"==s||"password"==s||"email"==
s||"tel"==s||"textarea"==s||"url"==s)v=lpmdec_acct(v,!0,a,g_shares);if(""!=v){verbose_log("Sending FillRequest: "+q+"\ntype="+s+"\nname="+r.name+"\nvalue=<hidden>");var w="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[a.aid]&&25E3>=(new Date).getTime()-g_last_launch[a.aid];console_log("Sending fillfield reqindex="+g_reqindex);var x={from:"fillfield_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;r={cmd:"fillfield",reqinfo:x,manualfill:l,
name:r.name,value:v,formname:r.formname,type:s,docid:f,aid:a.aid,checked:r.checked,doconfirm:c||a.save_all&&"password"==s?1:2,tabid:b,allowforce:g,custom_js:a.custom_js,sharedsite:p,otherfield:r.otherfield,domains:getacceptabletlds(a.url),automaticallyFill:j,is_launch:w,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0),from_iframe:h};""!=a.custom_js&&(r.username=getusernamefromacct(a),r.password=getpasswordfromacct(a),r.onlyfill=e?0:1);sendCS(b,r,d)}}}}}else g&&(console_log("no fields. finding best match "+
getusernamefromacct(a)+" and <hidden>"),w="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[a.aid]&&25E3>=(new Date).getTime()-g_last_launch[a.aid],console_log("Sending fillbest from A reqindex="+g_reqindex),x={from:"fillbest_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,sendCS(b,{cmd:"fillbest",reqinfo:x,username:getusernamefromacct(a),password:getpasswordfromacct(a),docid:f,aid:a.aid,custom_js:a.custom_js,updatefields:1,addurid:0,
sharedsite:p,domains:getacceptabletlds(a.url),automaticallyFill:j,is_launch:w,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)},d));g&&logLoginAndCheckWeakPassword(b,a);if(1!=c&&(q=check_autologin(e,a),"undefined"!=typeof AUTOSUBMIT&&(q=!0),"string"==typeof a.custom_js&&""!=a.custom_js&&sendCS(b,{cmd:"run_custom_js",docid:f,custom_js:a.custom_js,username:getusernamefromacct(a),password:lpmdec_acct(a.password,!0,a,g_shares),onlyfill:q?0:1,loc:3},d),("string"!=typeof a.custom_js||
-1==a.custom_js.indexOf("lpdontsubmit"))&&q))n="undefined"!=typeof a.submit_id?a.submit_id:"",p="undefined"!=typeof a.submit_html?a.submit_html:"",q="undefined"!=typeof a.submit_js?a.submit_js:"",is_guiless()&&"bankofamerica.com"==lp_gettld_url(a.url)||sendCS(b,{cmd:"submit",docid:f,submit_id:n,submit_html:p,submit_js:q},d)})}
function logLoginAndCheckWeakPassword(b,a){get_all_windows({populate:!0},function(f){for(var e=0;e<f.length;e++)for(var c=0;c<get_tabs_length(f[e]);c++){var d=get_tabs(f[e])[c];if(gettabid(d)==b&&(checkWeakAndDuplicate(a,b,lp_gettld_url(gettaburl(d))),(g_loglogins||LPISLOC)&&"undefined"==typeof g_loggedLogins[a.aid]))g_loggedLogins[a.aid]="1",loglogintab(a.aid,d)}})}function showpageoverlay(b){sendCS(b,{cmd:"showoverlay",urlprefix:getchromeurl("",!0)})}
function check_autologin(b,a){var f=!1;if(b)f=!0;else if(a.autologin){var e=(new Date).getTime(),c=parseInt(lpGetPref("autoautoVal",25));if(isNaN(c)||""==c||0>=c)c=25;c=e-1E3*c;"undefined"==typeof a.last_auto_login||isNaN(a.last_auto_login)||a.last_auto_login<c?(console_log("Launching autologin"),a.last_auto_login=e,f=!0):console_log("last autologin too soon!")}return f}
function fillfieldsconfirm(b){var a=b.url,f=b.result,e=b.aid,c=b.docid,d=b.tabid,g=b.doconfirm,k=b.from_iframe?!0:!1,l=b.manualfill,j=b.allowforce,m="undefined"!=typeof b.automaticallyFill?b.automaticallyFill:1,h=g_sites[e];if("undefined"!=typeof g_sites[e]){if(f&&(logLoginAndCheckWeakPassword(d,h),2==g)){k&&l&&sendCS(d,{cmd:"conditionalforcefill",reqinfo:p,username:getusernamefromacct(h),password:getpasswordfromacct(h),aid:h.aid,sharedsite:n,automaticallyFill:m,from_iframe:k},b.docnum);return}var n=
null!=h.sharedfromaid&&""!=h.sharedfromaid&&"0"!=h.sharedfromaid&&"null"!=h.sharedfromaid?1:0;if(h.save_all){if(!f||l){a="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[h.aid]&&25E3>=(new Date).getTime()-g_last_launch[h.aid];console_log("Sending fillbest from B reqindex="+g_reqindex);var p={from:"fillbest_B",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;sendCS(d,{cmd:"fillbest",reqinfo:p,username:getusernamefromacct(h),password:getpasswordfromacct(h),
docid:c,aid:h.aid,updatefields:0,addurid:0,sharedsite:n,domains:getacceptabletlds(h.url),automaticallyFill:m,is_launch:a,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)},b.docnum)}}else if(f){h=g_sites[e];l=j=null;k&&b.manualfill&&(j=l=!0);var q;fill(d,h,c,null,!1,b.docnum,j,!0,l,m,!1,k);delete g_fillfieldsmatches[a];delete g_fillfieldsmatchescurridx[a]}else if(b.allowforce)a="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[h.aid]&&25E3>=(new Date).getTime()-
g_last_launch[h.aid],console_log("Sending fillbest from C reqindex="+g_reqindex),p={from:"fillbest_C",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,sendCS(d,{cmd:"fillbest",reqinfo:p,username:getusernamefromacct(h),password:getpasswordfromacct(h),docid:c,aid:h.aid,updatefields:0,addurid:l?1:0,sharedsite:n,domains:getacceptabletlds(h.url),automaticallyFill:m,is_launch:a,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)},b.docnum);else{if(l=
g_fillfieldsmatches[a]){h=!1;for(n=0;n<l.length;n++){p=l[n].aid;if(h){(h=g_sites[p])&&(q=!1);fill(d,h,c,null,!0,b.docnum,null,!0,null,m,q,k);return}n==g_fillfieldsmatchescurridx[a]&&(g_fillfieldsmatchescurridx[a]++,h=!0)}}delete g_fillfieldsmatches[a];delete g_fillfieldsmatchescurridx[a]}}}
function web2plug(b){"2"==b.rsa?(g_local_key=AES.hex2bin(b.key),g_local_key_hex=b.key,g_local_key_hash=SHA256(g_local_key),rsa_userchangedpassword(),b=opendb(),createDataTable(b),b&&!LPISLOC&&b.transaction(function(a){a.executeSql("DELETE FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"accts"],function(){},function(a,b){console_log(b)})}),lpWriteKeyFile()):""!=g_username&&null!=g_username&&g_username!=b.username?loggedOut(!1,"web2plug"):(g_local_key=AES.hex2bin(b.key),
g_local_key_hex=b.key,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile())}function recover(b,a,f,e){var c=lpParseUri(a);a=c.directory;c=c.file;a=a.replace(/^\/~[^/]*/,"");""!=a&&"/"!=a&&"/sso/"!=a||"recover.php"==c&&GetOTPHash(null,b,f,e)}
function loginfromwebsite(b){if(""!=b.wxusername&&""!=b.keyhex){var a=opendb();createSavedLoginsTable(a);a&&a.transaction(function(c){var d=(new Date).getTime();c.executeSql("UPDATE LastPassSavedLogins2 SET last_login = ? WHERE username = ?",[d,b.wxusername],function(a,c){0==c.rowsAffected&&a.executeSql("INSERT INTO LastPassSavedLogins2 (username, password, last_login) VALUES (?, '', ?)",[b.wxusername,d])},function(a,b){console_log(b)});c.executeSql("SELECT * FROM LastPassSavedLogins2 WHERE username = ? AND password != ''",
[b.wxusername],function(c,d){if(0<d.rows.length){var e=d.rows.item(0).password,f=function(c){var d=get_key_iterations(b.wxusername);make_lp_key_iterations(b.wxusername,c,d,function(c){AES.bin2hex(c)!=b.keyhex&&a.transaction(function(a){a.executeSql("UPDATE LastPassSavedLogins2 SET password = '' WHERE username = ?",[b.wxusername],function(){},function(a,b){console_log(b)})})})};1==d.rows.item(0)["protected"]?unprotect_data(e,!1,f):2==d.rows.item(0)["protected"]&&f(lpdec(e,AES.hex2bin(SHA256(b.wxusername))))}},
function(){})});var f=AES.hex2bin(b.keyhex),e=null!=g_local_key?AES.bin2hex(g_local_key):"";if(!lploggedin||!(g_username==b.wxusername&&e==b.keyhex))lploggedin&&g_username==b.wxusername?(g_local_key=f,g_local_key_hex=b.keyhex,g_local_key_hash=SHA256(g_local_key)):(lploggedin&&""!=g_username&&loggedOut(!1,"differentuser"),""!=b.wxsessid&&(lp_phpsessid=b.wxsessid),g_local_key=f,g_local_key_hex=b.keyhex,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile(),LP.lplogincheck(!0,null,b.wxusername,b.wxhash))}else lploggedin||
LP.lplogincheck(!0)}
function reorderOnURL(b,a,f,e){var c=lpParseUri(a),d=lpcanonizeUrl(a,c),g="string"==typeof c.path?c.path.split("/"):[],k=lp_gettld_url(a),l=[],j;for(j in b)if(check_ident_aid(j)&&(b=g_sites[j],!("undefined"==typeof b||"undefined"==typeof b.url)))if(b.save_all||!f||!(""==b.unencryptedUsername&&""==b.password))if(!e||accthaspassword(b)){var m=lpParseUri(b.url);b.realmmatch=(a==g_basicauth_url||a==g_basicauth_origurl)&&(lpmdec_acct(b.realm_data,!0,b,g_shares)==g_basicauth_realm||g_basicauth_found&&""==
g_basicauth_realm&&1==b.basic_auth);b.servermatch=c.host==m.host;b.portmatch=compare_ports(c,m);b.serverportmatch=b.servermatch&&b.portmatch?1:0;b.usernamematch="undefined"!=typeof g_username_vals[a]&&""!=g_username_vals[a]&&g_username_vals[a]==b.unencryptedUsername;b.urlmatch=lpcanonizeUrl(b.url)==d?!0:!1;var m="string"==typeof m.path?m.path.split("/"):[],h;for(h=0;h<g.length&&h<m.length&&m[h]==g[h];h++);b.pathlevelmatch=h;b.fieldmatchcount=0;l.push(b)}l.sort(lp_aids_sort_func);return l=checkurlrules(g_urlrules,
l,k,"string"==typeof c.path?c.path:"",c.host,g_sites,get_port(c))}
function lp_aids_sort_func(b,a){return b.realmmatch!=a.realmmatch?b.realmmatch?-1:1:b.usernamematch!=a.usernamematch?b.usernamematch?-1:1:b.fav!=a.fav?"1"==b.fav?-1:1:b.urlmatch!=a.urlmatch?b.urlmatch?-1:1:b.serverportmatch&&a.serverportmatch&&b.pathlevelmatch!=a.pathlevelmatch?b.pathlevelmatch>a.pathlevelmatch?-1:1:b.serverportmatch!=a.serverportmatch?b.serverportmatch?-1:1:b.servermatch!=a.servermatch?b.servermatch?-1:1:b.fieldmatchcount!=a.fieldmatchcount?b.fieldmatchcount>a.fieldmatchcount?-1:
1:b.last_touch!=a.last_touch?b.last_touch>a.last_touch?-1:1:b.name!=a.name?b.name<a.name?-1:1:0}function lp_sort_case_insensitive_name(b,a){b=b.name.toLowerCase();a=a.name.toLowerCase();return b<a?-1:1}function launchautologin(b,a){if(check_ident_aid(b)){var f=g_sites[b];f&&(!a&&(f.pwprotect||g_prompts.login_site_prompt)?security_prompt(function(){launchautologin(b,!0)}):(g_last_launch[f.aid]=(new Date).getTime(),openURL(f.url,function(a,b){g_launches[gettabid(a)]=b},f.aid)))}}
function hasNeverShowIcon(b,a){var f=lpcanonizeUrl(b);if(g_neverurls.onlyshowicons&&0<g_neverurls.onlyshowicons.length){for(var e=!1,c=0;g_neverurls.onlyshowicons&&c<g_neverurls.onlyshowicons.length;c++){var d=g_neverurls.onlyshowicons[c];if(d==a||d==f){e=!0;break}}if(!e)return!0}for(c=0;g_neverurls.nevershowicons&&c<g_neverurls.nevershowicons.length;c++)if(d=g_neverurls.nevershowicons[c],d==a||d==f)return!0;return!1};
