var gLastLoginState=0,gAccts_version=-1,gCurr_username="",gTimerId=null,gIconsLength=0,gLastSearch="",gIdentity="",gSearchWhileType=!0,gTreeHeightOffset=147,gPollInterval=500,gHidePreferences=!1,gLocalBaseUrl="",g_hideprofilecopy=1,g_hideidentcopy=1,g_localvault=1,g_showrows=1,g_autoselectcredmontab=0,g_partnername="",g_hideenterprisetab=!1,g_CNTsearch_it=0,g_CNTsearch_string_tokenize=0,g_CNTinit_vault=0,g_CNTpopulate=0,g_CNTsearch_tree=0,g_CNTclear_tree=0,event_handlers={},event_handlers_onmouseover=
{},event_handlers_onmouseout={},event_handlers_onclick={};function getpartnerurl(a){""!=g_partnername&&(a+=(0<=a.indexOf("?")?"&":"?")+"partnername="+encodeURIComponent(g_partnername));return a}function fix_group(a){a==gs("(none)")&&(a="");return a}
function onLoad(a,b){try{if("undefined"!=typeof g_is_safari&&"undefined"==typeof LPFromWebsite)50>a?(a++,setTimeout(function(){onLoad(a)},25)):document.location.href=document.location.href;else if("undefined"==typeof g_is_safari&&!b)get_data("vault",function(){onLoad(a,!0)});else if("function"!=typeof getBG||"undefined"==typeof getBG()||null==getBG())setTimeout(function(){onLoad()},50);else{g_urlprefix=getBG().base_url;var c=document.createElement("base");c.href=g_urlprefix;document.head.appendChild(c);
0<document.location.href.lastIndexOf("/")&&(gLocalBaseUrl=document.location.href.substr(0,document.location.href.lastIndexOf("/")+1));getBG().LPISLOC&&(document.getElementById("accountsettingscontainer").style.display="none");getBG().g_hideidentities&&(document.getElementById("identitycontainer").style.display="none");getBG().g_hideseccheck&&(document.getElementById("seccheckcontainer").style.display="none");sr(document,"submit","value","Searchproper");document.getElementById("q").setAttribute("placeholder",
gs("Search Vault"));document.getElementById("lpusername").innerHTML="<b><a href='' id='lpusernamelink'>"+gs("Login")+"</a></b>";document.getElementById("lpusernamelink").onclick=function(){return login()};onResize();inittabs();setusernametext(getBG().g_username);0<document.location.href.indexOf("cmd=video")&&ontabchange(document.getElementById("video"));gTimerId=setInterval(function(){checkLoggedInHome()},gPollInterval);var f=getcolvisibility("usernamecol"),g=getcolvisibility("ltnamecol");document.getElementById("usercol").className=
f?"usercolvisible":"usercolhidden";document.getElementById("ltcol").className=g?"ltcolvisible":"ltcolhidden";document.getElementById("ltcol").style.paddingRight=f?"calc(5% + 20px)":"5%";create_combo("grpsel",[]);document.getElementById("grpsel_combo").style.height="150px";document.getElementById("grpsel_combo").style.overflow="auto";document.getElementById("q").focus();document.getElementById("ident").style.display=getBG().g_hideidentities?"none":"table-cell";document.getElementById("shares").style.display=
getBG().g_hidesharing?"none":"table-cell";document.getElementById("addsecurenote").style.display=getBG().g_hidenotes?"none":"block";document.getElementById("import").style.display=getBG().g_hideimport?"none":"block";document.getElementById("export").style.display=getBG().g_hideexport?"none":"block"}}catch(j){alert("homelocal2 onLoad:"+j)}}function onUnLoad(){gTimerId&&(clearInterval(gTimerId),gTimerId=null);saveGroupState()}
function onResize(){for(var a=0;a<tabnames.length;a++)document.getElementById(tabnames[a])&&(document.getElementById(tabnames[a]).style.height=document.body.clientHeight-gTreeHeightOffset+20+"px");document.getElementById("thetree")&&(document.getElementById("thetree").style.height=document.body.clientHeight-gTreeHeightOffset-14+"px")}
function checkLoggedInHome(a){try{var b=getBG(),c=b.lploggedin;if(("undefined"!=typeof g_issafari&&g_issafari||"undefined"!=typeof g_isopera&&g_isopera||"undefined"!=typeof g_ismaxthon&&g_ismaxthon)&&!a)b.update_state("vault");else{a="";c&&(a=b.g_username);if(c!=gLastLoginState||a!=gCurr_username)if(c)window_load_loggedin(a);else{try{var f={"static":"{}"};$(function(){$("#thetree").tree({data:{type:"json",opts:f}})})}catch(g){}finish_vault_search();g_lastnodeid=g_rootnodeid=null;window_load_loggedoff();
update_identity_popup()}gLastLoginState=c;g_username=lpusername=gCurr_username=a;if(gLastLoginState){var j=b.g_local_accts_version;if(j>gAccts_version||b.IsIconsUpdated(gIconsLength)||b.g_identity!=gIdentity)finish_vault_search(),gAccts_version=j,populateNewData(gLastSearch),populateff(gLastSearch),populateident(gLastSearch),update_identity_popup(),setusernametext(a),showads()}}}catch(k){alert("checkLoggedInHome:"+k)}}
function setusernametext(a){var b=getBG();if(b.lploggedin){var c="",f;for(f in b.g_identities)if(b.g_identities.hasOwnProperty(f)&&b.g_identity==b.g_identities[f].iid){c=b.g_identities[f].deciname;break}""==c?document.getElementById("lpusername").innerText=of(a):document.getElementById("lpusername").innerText=of(a+" ("+c+")")}else document.getElementById("lpusername").innerText=gs("Login")}
function window_load_loggedin(a){document.getElementById("identity").disabled=0;document.getElementById("enterpriseaction").style.display=!g_hideenterprisetab&&getBG().g_iscompanyadmin?"":"none";document.getElementById("enterprise").style.display=g_hideenterprisetab||"1"==getBG().g_enterpriseuser?"none":"";document.getElementById("addsharedfolder").style.display="";document.getElementById("credmon").style.display="1"==getBG().g_showcredmon?"":"none";"1"==getBG().g_enterpriseuser&&(document.getElementById("linkpersonal").style.display=
!g_hideenterprisetab&&""==get_personal_linked()?"":"none",document.getElementById("removepersonal").style.display=!g_hideenterprisetab&&""!=get_personal_linked()?"":"none");setusernametext(a);getBG().get_securityChallengeScore(function(a){a&&(document.getElementById("securitycheckscore").style.color=getscorecolor(a),document.getElementById("securitycheckscore").innerHTML=" ("+getscoretxt(a)+")")});g_local_key=getBG().g_local_key;g_key_iterations=getBG().get_key_iterations(a)}
function showads(){getBG().lploggedin&&getBG().g_premium_exp<lp_get_local_timestamp()&&"1"!=getBG().g_enterpriseuser&&-1==document.location.href.indexOf("cmd=video")?("none"==document.getElementById("adframe").style.display&&(document.getElementById("adframe").style.display="block",document.getElementById("rightside").style.display="block",document.getElementById("adframe").setAttribute("src",getpartnerurl(g_urlprefix+"ads.php?nobr=1&noga=1&rand="+Math.floor(1E3*Math.random())))),document.getElementById("friend").style.display=
"block"):(document.getElementById("adframe").style.display="none",document.getElementById("rightside").style.display="none",document.getElementById("friend").style.display="none")}
function window_load_loggedoff(){gAccts_version=-1;gIconsLength=0;g_local_key=null;document.getElementById("lpusername").innerHTML="<b><a href='' id='lpusernamelink'>"+gs("Login")+"</a></b>";document.getElementById("lpusernamelink").onclick=function(){return login()};document.getElementById("credmon").style.display="none";document.getElementById("adframe").style.display="none";document.getElementById("rightside").style.display="none";document.getElementById("friend").style.display="none";document.getElementById("enterpriseaction").style.display=
"none";document.getElementById("enterprise").style.display=g_hideenterprisetab?"none":"";document.getElementById("addsharedfolder").style.display="none";document.getElementById("linkpersonal").style.display="none";document.getElementById("removepersonal").style.display="none";for(var a=0;a<tabnames.length;a++)"treepane"!=tabnames[a]&&cleartab(tabnames[a]);setusernametext(getBG().g_username);document.getElementById("securitycheckscore").innerHTML=""}
function populateNewData(a){var b=!1,c;for(c in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(c)){b=!0;break}if(!b)for(c in getBG().g_securenotes)if(getBG().g_securenotes.hasOwnProperty(c)){b=!0;break}var f=!1;for(c in getBG().g_pendings)if(getBG().g_pendings.hasOwnProperty(c)){f=!0;break}!b&&!f?document.getElementById("sitesiframe")||(b=document.getElementById("treepane"),a=document.createElement("iframe"),a.id="sitesiframe",a.className="overviewiframe",a.src=getpartnerurl("sites_overview.php"),
b.appendChild(a),document.getElementById("thetree").style.display="none"):(document.getElementById("sitesiframe")&&(b=document.getElementById("treepane"),b.removeChild(document.getElementById("sitesiframe")),document.getElementById("thetree").style.display=""),populate(a,!0),SearchTree(0,!0))}function isSafariNative(){return"undefined"!=typeof LPFromWebsite&&("undefined"==typeof g_issafari||!g_issafari)}function showhide(a,b){document.getElementById(a).style.display=b?"":"none"}
function update_identity_popup(){for(var a=getBG(),b=document.getElementById("identity");b.length;)b.remove(0);var c=document.createElement("option");c.text=gs("All");c.value="";""==a.g_identity&&(c.selected=1);b.appendChild(c);var f=0,g;for(g in a.g_identities)a.g_identities.hasOwnProperty(g)&&(c=document.createElement("option"),c.text=a.g_identities[g].deciname,c.value=a.g_identities[g].iid,a.g_identity==a.g_identities[g].iid&&(c.selected=1),b.appendChild(c),f++);0<f&&!getBG().g_hideidentities?
document.getElementById("identitycontainer").style.display="":document.getElementById("identitycontainer").style.display="none";document.getElementById("identitylabel").innerHTML=gs("Identity")}
function search_matches(a,b){var c=getBG(),c=c.g_prompts.edit_sn_prompt?!1:c.get_searchNotesPref();g_CNTsearch_matches++;var f=getBG().g_sites[a];if("undefined"==typeof f&&(f=getBG().g_securenotes[a],"undefined"==typeof f&&(0==a.indexOf("app")&&(a=a.substring(3)),f=getBG().g_applications[a],"undefined"==typeof f&&(f=getBG().g_pendings[a],"undefined"==typeof f)))){var g=getgroupnamefromid(a);if(g)for(var j in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(j)&&"undefined"!=typeof getBG().g_sites[j]&&
"http://group"==getBG().g_sites[j].url&&getBG().g_sites[j].group==g){f=getBG().g_sites[j];break}if("undefined"==typeof f)return!1}return matches(f,b,c)}var g_all_li=[],g_search_array={};function init_vault_search(){g_all_li=$("#thetree").find("li");g_CNTinit_vault++;var a=getBG(),a=a.g_prompts.edit_sn_prompt?!1:a.get_searchNotesPref();g_search_array=sites_tokenize(g_all_li,a)}function finish_vault_search(){lastqstr=g_search_array=g_all_li=null}
function sites_tokenize(a,b){for(var c={},f=0;f<a.length;f++){var g=a[f].id,j="id"+g,k="",h=getBG().g_sites[g];if("undefined"==typeof h&&(h=getBG().g_securenotes[g],"undefined"==typeof h&&(0==g.indexOf("app")&&(g=g.substring(3)),h=getBG().g_applications[g],"undefined"==typeof h&&(h=getBG().g_pendings[g],"undefined"==typeof h))))if(g=getgroupnamefromid(g))k=g;else if("undefined"==typeof h)continue;if(k)h=k.toLowerCase(),c[j]=h;else if("undefined"!=typeof h){k=[];k.push(h.name);k.push(h.group);"http://group"!=
h.url&&"http://sn"!=h.url&&k.push(h.url);h.unencryptedUsername&&k.push(h.unencryptedUsername);is_application(h)&&(k.push(h.appname),k.push(getusernamefromacct(h)));if(b&&"undefined"!=typeof h.extra&&0<h.extra.length&&("undefined"==typeof h.url||"http://group"!=h.url)&&!h.pwprotect)g=getBG().lpmdec_acct(h.extra,!0,h,getBG().g_shares),(!g||0==g.length)&&console.log("searchinnotes: site aid="+h.aid+" FAILED TO DECRYPT"),k.push(g);h=k.join(" ");h=h.toLowerCase();c[j]=h}}return c}
function search_string_tokenize(a){var b=[];g_CNTsearch_string_tokenize++;if(!a)return b;if(-1==a.indexOf('"'))b=a.split(/\s+/);else{var c=[],c=a.split('"');for(a=0;a<c.length;a++)if(a%2)b.push(c[a]);else for(var f=[],f=c[a].split(/\s+/),g=0;g<f.length;g++)f[g]=f[g].replace(/^\s+/,""),f[g]=f[g].replace(/\s+$/,""),0<f[g].length&&b.push(f[g])}return b}
function search_it(a,b){g_CNTsearch_it++;for(var c="id"+a,f=1,g=0;g<b.length;g++)if(!(g_search_array[c]&&-1!=g_search_array[c].indexOf(b[g]))){f=0;break}return f}var populate_done=!1;
function populate(a,b){try{var c=getBG();g_CNTpopulate++;c.g_prompts.edit_sn_prompt||c.get_searchNotesPref();var f=$("#q").val(),g=0;a!=f&&($("#q").val(a),f=a,g=0);gLastSearch=a;gIconsLength=c.g_icons_length;gIdentity=c.g_identity;var f=[],j=[],k=[],h=[],n=[],l=0,w=[c.g_sites,c.g_securenotes],u;for(u in w)if(w.hasOwnProperty(u)){var z=w[u],m;for(m in z)if(z.hasOwnProperty(m)&&(l++,c.check_ident_aid(m))){for(var p=z[m],v=""!=p.group?p.group:"http://sn"==p.url?gs("Secure Notes"):gs("(none)"),v="_"+
v;"\\"==v[0];)v=v.substr(1);"undefined"==typeof f[v]&&(f[v]=[],j[j.length]=v,k[v]="undefined"==typeof p.aid?null:p.aid);f[v][f[v].length]=p;n[n.length]=p;"1"==p.fav&&(h[h.length]=p)}}for(m in c.g_applications)c.g_applications.hasOwnProperty(m)&&c.check_ident_appaid(m)&&(p=c.g_applications[m],v=""!=p.group?p.group:gs("(none)"),v="_"+v,"undefined"==typeof f[v]&&(f[v]=[],j[j.length]=v,k[v]="undefined"==typeof p.aid?null:p.aid),f[v][f[v].length]=p,n[n.length]=p,"1"==p.fav&&(h[h.length]=p));var w=0,q;
for(q in c.g_pendings)c.g_pendings.hasOwnProperty(q)&&(++w,p=c.g_pendings[q],""==a&&(v=gs("(New Pending Share Offers)"),"undefined"==typeof f[v]&&(f[v]=[],j[j.length]=v,k[v]=null),f[v][f[v].length]=p));var F=j.length;j.sort(function(a,b){return"_Apps assigned to me"==a?-1:"_Apps assigned to me"==b?1:a.toLowerCase()<b.toLowerCase()?-1:1});n.sort(function(a,b){return a.last_touch>b.last_touch?1:-1});var p=[],y=c.getClearRecentTime(),C=c.getRecentCount();if(""==a)for(q=0;p.length<C&&q<n.length;q++)"http://group"!=
n[n.length-q-1].url&&(n[n.length-q-1].last_touch<y||(p[p.length]=n[n.length-q-1]));if(p.length){var x=gs("recently usedlower");j.unshift(x);f[x]=p}h.length&&(j.unshift(gs("favorites")),f[gs("favorites")]=h);y=[];""==a&&(y=getOpenedGroups());var r=[],C=[];resetgroupnames();event_handlers={};event_handlers_onmouseover={};event_handlers_onmouseout={};event_handlers_onclick={};for(q=0;q<j.length;q++){x=!1;if(""!=a||"undefined"!=typeof y[j[q]]||1==F&&q==j.length-1)x=!0;var D="undefined"==typeof k[j[q]]?
null:k[j[q]];"undefined"!=typeof j[q]&&addGroup(c,f,r,C,j[q],x,!1,y,D)}$(function(){var a={};a["static"]=r;var b={beforedelete:lpbeforedelete,beforemove:lpbeforemove,onmove:lponmove,check_move:lpcheck_move,onselect:lponselect};populate_done||(b.onrgtclk=lponrgtclk);$("#thetree").tree({callback:b,data:{type:"json",opts:a},rules:{multiple:"ctrl",drag_copy:!1,use_max_children:!1,use_max_depth:!1},plugins:{hotkeys:{functions:{"return":function(){var a=$.tree.focused().selected;a&&(1==a.length&&(isNumber(a[0].id)||
is_application(a[0].id)))&&ls(a[0].id)}}}}})});$(".shareimggroup").click(function(){var a=$(this).closest("li").get();a.length&&(a=getgroupnamefromid(a[0].id),0==a.indexOf("_")&&(a=a.substring(1)),0==a.indexOf("Shared-")?manageSharedFolder(a):shareFolder(a))});$(".toolsimg").click(function(){var a=$(this).closest("li").get();if(a.length){var a=a[0],b=getgroupnamefromid(a.id);0==b.indexOf("_")&&(b=b.substring(1));openGroupMenu(a,b,t,event)}});$(".folder").mouseover(function(){sv(null,this)});$(".folder").mouseout(function(){hv(null,
this)})}catch(A){if("undefined"==typeof LPFromWebsite||"function"!=typeof LPFromWebsite.ipad){if(0<=A.message.indexOf("atob")&&-1==document.location.href.indexOf("retry")){document.location.href+="?retry=1";return}alert("populate_error:"+A)}}update_identity_popup();init_vault_search();populate_done=!0;a&&""!=a&&SearchTree(g,b);for(q in event_handlers)document.getElementById(q)&&(document.getElementById(q).onclick=event_handlers[q]);for(q in event_handlers_onmouseover){c=document.getElementsByName(q);
for(g=0;g<c.length;g++)c[g].onmouseover=event_handlers_onmouseover[q]}for(q in event_handlers_onmouseout){c=document.getElementsByName(q);for(g=0;g<c.length;g++)c[g].onmouseout=event_handlers_onmouseout[q]}for(q in event_handlers_onclick){c=document.getElementsByName(q);for(g=0;g<c.length;g++)c[g].onclick=event_handlers_onclick[q]}}
function lpbeforedelete(a){var b=getBG();if(1<($.tree.focused().selected_arr&&$.tree.focused().selected_arr.length)){for(var c="",f=[],g=0;g<$.tree.focused().selected_arr.length;g++){var j=getmoveid($.tree.focused().selected_arr[g]);j&&""!=j&&(c+=(""!=c?",":"")+j,f[f.length]=$.tree.focused().selected_arr[g])}b.deleteAid(c,window,!1,!1,function(){for(var a=0;a<f.length;a++)$.tree.focused().cut(f[a])});return!1}c=!1;is_application(a.id)||isNumber(a.id)?c=b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)}):
(c=getgroupnamefromid(a.id),c=b.deleteGroup(fix_group(c),window,function(){$.tree.focused().cut(a)}));return c}
function lpbeforemove(a,b){getBG().lpevent("v_dnd");for(var c="",f=b,c=0;f&&""==f.attr("id")&&100>c;)f=f.parent(),c++;if(99<c||!f)return!1;var g=f.attr("id");g.match(/launch_(nor|fav|rec)_\d+/)&&(g=g.substr(11));g.match(/accept2_(nor|fav|rec)_\d+/)&&(g=g.substr(12));var c="",j=getBG();if(is_application(g)||isNumber(g)){is_application(g)?(j=[j.g_applications],g=get_appaid(g)):j=[j.g_sites,j.g_securenotes];for(var k in j)if(j.hasOwnProperty(k)){var h=j[k],n;for(n in h)if(h.hasOwnProperty(n)){var l=
h[n];if(l.aid==g){if("1"==l.fav){h=f.parent();for(c=0;h&&""==h.attr("id")&&100>c;)h=h.parent(),c++;if(99>c&&h&&h.attr("id")==gs("favorites")){c=gs("favorites");break}}c=l.group;break}}}}else c=getgroupnamefromid(g);f=gs("recently usedlower");if(!(""==c||c==f||c==gs("(New Pending Share Offers)"))){f=$.tree.focused().selected_arr;k="";for(n=0;n<f.length;n++)if(is_application(getmoveid(f[n]))||isNumber(getmoveid(f[n])))k+=(""==k?"":",")+getmoveid(f[n]);0==k.length&&(k=a.attr("id"));0!=k.length&&getBG().moveSelectedToGroup(c,
k);return!1}}function lponmove(){}function lpcheck_move(a){return 1<$.tree.focused().selected_arr.length?!0:a&&""!=a.attr("id")&&!is_application(a.attr("id"))&&!isNumber(a.attr("id"))?!1:!0}function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}var g_groups={},g_groupindex=2E5,g_groupid={},g_groupnames={};function getgroupnamefromid(a,b){if("undefined"==typeof g_groups[a])return a;var c=g_groups[a];!b&&0==c.indexOf("_")&&(c=c.substring(1));return c}
function getrawgroupid(a){return"undefined"==typeof g_groupid[a]||null==g_groupid[a]?null:g_groupid[a]}function resetgroupnames(){g_groups={};g_groupindex=2E5;g_groupid={};g_groupnames={}}function getgroupid(a,b){var c="LpGrOuP"+g_groupindex;g_groups[c]=a;g_groupnames[a]=c;g_groupid[c]=b;++g_groupindex;return"LpGrOuP"+(g_groupindex-1)}function getgroupidfromname(a){return"undefined"==typeof g_groupnames[a]||null==g_groupnames[a]?null:g_groupnames[a]}var g_rootnodeid=null,g_lastnodeid=null;
function addGroup(a,b,c,f,g,j,k,h,n){for(;"\\"==g[0];)g=g.substr(1);for(var l=g.match(/^([^\\]*)\\(.*)$/),w=null!=l,u="",z=0;l&&!k;){var m=l[1],p=l[2],u=u+((""!=u?"\\":"")+m);"undefined"==typeof f[u]&&addGroup(a,b,c,f,u,j||"undefined"!=typeof h[u],!0,h,n);z++;l=p.match(/^([^\\]*)\\(.*)$/)}u=(""==u?"":"\\")+g;k=[];j=j?"open":"closed";b=b[g];"undefined"==typeof b&&(b=[]);m=gs("recently usedlower");h="nor_";g!=m&&g!=gs("(New Pending Share Offers)")?(b.sort(a.lp_sort_case_insensitive_name),g==gs("favorites")&&
(h="fav_")):(b.sort(function(a,b){return a.last_touch>b.last_touch?-1:1}),g==m&&(h="rec_"));for(var v=getcolvisibility("usernamecol"),q=getcolvisibility("ltnamecol"),F=navigator.userAgent.match("Gecko/"),y=1==g_showrows?"":"none",C=0;C<b.length;C++){var x=45+15*z;if(F||"undefined"!=typeof g_isopera&&g_isopera)x+=20;var r=b[C];if("http://group"!=r.url){l=m="";if("undefined"!=typeof r.sharerusername)"undefined"!=typeof g_isopera&&g_isopera&&(m+="</a>"),m+="<div class='actionmenu' style='padding-right: "+
x+"px;display:"+y+";'><a href='#' id='accept_"+h+r.id+"' style='text-decoration: underline; color: #00C'><img src='"+gLocalBaseUrl+"images/vaultaccept.png'/></a> | <a href='#' id='reject_"+h+r.id+"' style='text-decoration: underline; color: #00C'><img src='"+gLocalBaseUrl+"images/vaultreject.png'/></a></div>",event_handlers["accept_"+h+r.id]=function(){return accept(this.id.substring(11))},event_handlers["reject_"+h+r.id]=function(){return reject(this.id.substring(11))},m+="<span style='clear:both'></span>",
m+="<span><a href='#' id='accept2_"+h+r.id+"'>"+gs("Share offer from")+" "+of(a.hex2bin(r.sharerusername))+"</a></span>",event_handlers["accept2_"+h+r.id]=function(){return accept(this.id.substring(12))};else{var D=safclassdel=safclassshare="";if(g_issafari||g_isopera)D=" editsaf",safclassdel=" delsaf",safclassshare=" sharesaf";var l=get_record_id(r),A,B="<a href='#' id='share_"+h+l+"' style='text-decoration: underline; color: #00C' title='"+gs("Share")+"'><span class='shareimg"+safclassshare+"'></span></a> ";
event_handlers["share_"+h+l]=function(){return s(this.id.substring(10))};!a.LPISLOC&&!r.genpw&&("undefined"==typeof r.sharedfromaid||null==r.sharedfromaid||""==r.sharedfromaid||"0"==r.sharedfromaid||"null"==r.sharedfromaid)&&"undefined"==typeof r.sharefolderid&&!is_application(r)&&!1==a.g_hidesharing?A="":(A='<font style="visibility: hidden;display:inline;">'+B+"</font>",B="");var E="",G="undefined"!=typeof r.sharedfromaid&&"0"!=r.sharedfromaid?r.sharedfromaid:"";"undefined"!=typeof r.hasbeenshared&&
1==r.hasbeenshared?(E="<p class='sharesubtext'><subtext id='sharesub_"+h+l+"'>"+gs("shared")+"</subtext></p>",event_handlers["sharesub_"+h+l]=function(){return s(this.id.substring(13))}):r.individualshare&&(""==G?(E="<p class='sharesubtext'><subtext id='sharesub_"+h+l+"'>"+gs("shared")+"</subtext></p>",event_handlers["sharesub_"+h+l]=function(){return s(this.id.substring(13))}):E="<p class='sharesubtext'>"+gs("shared with you")+"</p>");"undefined"!=typeof g_isopera&&g_isopera&&(m+="</a>");m+="<div class='actionmenu' style='padding-right: "+
x+"px; display:"+y+";'>"+A;m+="<a href='#' id='edit_"+h+l+"' style='text-decoration: underline; color: #00C' title='"+gs("Edit")+"'><span class='editimg"+D+"'></span></a> ";event_handlers["edit_"+h+l]=function(){return e(this.id.substring(9))};m+=B;m+="<a href='#' id='delete_"+h+l+"' style='text-decoration: underline; color: #00C' title='"+gs("Delete")+"'><span class='delimg"+safclassdel+"'></span></a></div>";event_handlers["delete_"+h+l]=function(){return d(this.id.substring(11))};m+="<span style='clear:both'></span>";
m+="<span><a href='#' id='launch_"+h+l+"'>"+of(r.name)+"</a>"+E+"</span>";event_handlers["launch_"+h+l]=function(){return ls(this.id.substring(11))}}x="calc(5% + 10px)";D=v?"usercolvisible":"usercolhidden";A=q?"ltcolvisible":"ltcolhidden";B=of(a.getusernamefromacct(r));""==B&&(B="&nbsp;");m+="<div style='float: right; padding-right: "+x+";display:"+y+";' class='"+D+"' name='usercol'>"+B+"</div>";m+="<div style='float: right; padding-right: "+x+";display:"+y+";' class='"+A+"' name='ltcol'>"+("undefined"!=
typeof r.last_touch?of(elapsedTime(r.last_touch)):"")+"</div>";k[k.length]={data:{title:m,icon:a.geticonurlfromrecord(r)},attributes:{id:l,name:l}};event_handlers_onmouseover[l]=function(){sv(event,this);return!1};event_handlers_onmouseout[l]=function(){hv(event,this);return!1};event_handlers_onclick[l]=function(){lc(event,this);return!1}}}a=g;0==a.indexOf("_")&&(a=a.substring(1));m=30+15*z;m=g===gs("favorites")||g==gs("recently usedlower")||g==gs("(New Pending Share Offers)")?"":"<div class='actionmenu' style='padding-right: "+
m+"px;'>"+("1"==getBG().g_enterpriseuser&&!is_personal_linked(a)?"<a href='#' title='"+gs("Share")+"'><span class='shareimggroup'></span></a> ":"")+"<a href='#' title='"+gs("Group Actions")+"'><span class='toolsimg'></span></a></div>";m+="<span style='font-weight:bold' isgroup='1' >"+of(a)+"</span>";f[g]=c.length;if(w){l=g.match(/^([^\\]*)\\(.*)$/);f=null;for(w=u=0;l;){m=l[1];p=l[2];if(0==u){for(b=c.length-1;0<=b;b--)if(c[b].group==m){f=c[b].children;break}w=0;u=1;if(!p.match(/^([^\\]*)\\(.*)$/))for(b=
0;b<f.length;b++)if("undefined"==typeof f[b].group||f[b].group==m){w=b;break}}else{for(b=l=0;b<f.length;b++)if("undefined"==typeof f[b].group){l=b-1;break}else if(f[b].group==m){l=b;break}f=f[l].children}l=p.match(/^([^\\]*)\\(.*)$/);if(!l)for(b=0;b<f.length;b++)if("undefined"==typeof f[b].group||f[b].group==m){w=b;break}else if(b==f.length-1){w=b+1;break}}l=getgroupid(g,n);m="<div class='actionmenu' style='padding-right: "+(30+15*z)+"px;'>"+("1"==getBG().g_enterpriseuser&&!is_personal_linked(a)?
"<a href='#' title='"+gs("Share")+"'><span class='shareimggroup'></span></a> ":"")+"<a href='#' title='"+gs("Group Actions")+"'><span class='toolsimg'></span></a></div>";m+="<span style='font-weight:bold' isgroup='1'>"+of(p)+"</span>";f.splice(w,0,{data:m,children:k,state:j,group:p,attributes:{"class":"folder",id:l}})}else 0==c.length&&(g_rootnodeid=g),g_lastnodeid=g,l=getgroupid(u,n),n=g.indexOf("Shared-"),c[c.length]={data:m,children:k,state:j,group:g,attributes:{"class":"folder"+(0==n||1==n?" shared":
""),id:l}}}function getcolvisibility(a){return 0==localStorage.getItem(a)?!1:!0}function setcolvisibility(a,b){localStorage.setItem(a,b)}
function matches(a,b,c){var f=b.toLowerCase();g_CNTmatches++;if(-1!=a.name.toLowerCase().indexOf(f)||(a.url&&-1!=a.url.toLowerCase().indexOf(f)||-1!=a.group.toLowerCase().indexOf(f)||a.unencryptedUsername&&-1!=a.unencryptedUsername.toLowerCase().indexOf(f))||is_application(a)&&(a.appname&&-1!=a.appname.toLowerCase().indexOf(f)||-1!=getusernamefromacct(a).toLowerCase().indexOf(f)))return!0;if(c&&"undefined"!=typeof a.extra&&0<a.extra.length&&("undefined"==typeof a.url||"http://group"!=a.url))if(c=
getBG().lpmdec_acct(a.extra,!0,a,getBG().g_shares),g_CNTmatches_decrypt++,-1!=c.toLowerCase().indexOf(f))return!0;return"has:attachment"==b&&"undefined"!=typeof a.attachid&&null!=a.attachid&&0!=a.attachid?!0:!1}
function getOpenedGroups(){var a=getBG(),b=[],c="";if("undefined"==typeof LPFromWebsite){if("undefined"==typeof localStorage)return b;c=localStorage.getItem(a.db_prepend(a.g_username_hash+".savedtree"));c=a.dec(c)}else c=LPFromWebsite.readopengroups();if(!c||""==c)return b;a=c.split(",");for(c=0;c<a.length;c++)b[a[c].replace("%2C",",")]=1;return b}
function saveGroupState(){var a=getBG();if(!massoperation&&a.lploggedin){var b="",c=$("#thetree").find(".open");$.each(c,function(a,c){var j=getgroupnamefromid(c.id,!0);j.replace(",","%2C");b+=j+","});"undefined"==typeof LPFromWebsite?"undefined"!=typeof localStorage&&(c=a.enc(b),localStorage.setItem(a.db_prepend(a.g_username_hash+".savedtree"),c)):LPFromWebsite.saveopengroups(b)}}function lc(a,b){$.tree.focused().select_branch(b,a.ctrlKey|a.metaKey,a.shiftKey)}
function sv(a,b){$(b).children(".actionmenu").find("span").each(function(){$(this).css("opacity","1.0")});if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="inline-block")}function hv(a,b){$(b).children(".actionmenu").find("span").each(function(){$(this).css("opacity","0.2")});if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="none")}function lponopen(){saveGroupState()}
function lponclose(){saveGroupState()}function lponselect(){document.getElementById("q").blur()}var g_lastpop=0;
function lponrgtclk(a,b,c){var f=$.tree.focused().selected_arr&&$.tree.focused().selected_arr.length;getBG().lpevent("v_rgt");var g=(new Date).getTime();if(!(g_lastpop>g-500)){g_lastpop=g;if(1<f){for(var j="",k=[],h=!1,n=!1,f=0;f<$.tree.focused().selected_arr.length;f++)if((g=getmoveid($.tree.focused().selected_arr[f]))&&""!=g)is_application(g)&&(h=!0),get_record(g)&&"undefined"!=typeof get_record(g).sharefolderid&&(n=!0),j+=(""!=j?",":"")+g,k[k.length]=$.tree.focused().selected_arr[f];setTimeout(function(){$.contextMenu.create(function(){var b=
getBG(),c={};c[gs("Move Selected to Group")]=function(){b.lpevent("v_multmov");openMoveGroup(a)};!h&&!n&&(c[gs("Share Selected")]=function(){b.lpevent("v_mults");s(j)});c[gs("Delete Selected")]=function(){b.lpevent("v_multd");b.deleteAid(j,window,!1,!1,function(){for(var a=0;a<k.length;a++)$.tree.focused().cut(k[a])})};return[c]},{theme:"vista"}).show(b,c)},100)}else if("undefined"!=typeof a)if(""!=a.id&&!is_application(a.id)&&!isNumber(a.id)){f=getgroupnamefromid(a.id);0==f.indexOf("_")&&(f=f.substring(1));
for(var g=!1,l=a;l.parentNode&&l.parentNode!=l;)if(l=l.parentNode,"thetree"==l.id){g=!0;break}if(!g)return;openGroupMenu(a,f,b,c);c.preventDefault()}else""!=a.id&&(is_application(a.id)||isNumber(a.id))&&setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={};if("undefined"!=typeof getBG().g_sites[a.id]||is_application(a.id)){if("undefined"==typeof g_issafari&&"undefined"==typeof g_isopera&&"undefined"==typeof g_ismaxthon||"function"==typeof b.can_copy_to_clipboard&&b.can_copy_to_clipboard()||
"undefined"!=typeof g_is_safari)c[gs("Copy Username")]=function(){b.copyusername(a.id)},c[gs("Copy Password")]=function(){b.copypassword(a.id)},c[gs("Copy URL")]=function(){b.copyurl(a.id)}}else if("undefined"!=typeof getBG().g_securenotes[a.id]){var f=getBG().g_securenotes[a.id],f="undefined"!=typeof f.notetype?f.notetype:"";"undefined"!=typeof sntemplates[f]&&"undefined"!=typeof sntemplates[f].Username&&(c[gs("Copy Username")]=function(){b.copyusername(a.id)});"undefined"!=typeof sntemplates[f]&&
"undefined"!=typeof sntemplates[f].Password&&(c[gs("Copy Password")]=function(){b.copypassword(a.id)})}c[gs("Move to Group")]=function(){b.lpevent("v_mov");openMoveGroup(a)};c[gs("Move to Sub-Group")]=function(){b.lpevent("v_msub");openMoveGroup(a,!0)};f=get_record(a.id);if(!is_application(a.id)&&get_record(a.id)&&"undefined"==typeof get_record(a.id).sharefolderid&&("undefined"==typeof f.sharedfromaid||null==f.sharedfromaid||""==f.sharedfromaid||"0"==f.sharedfromaid||"null"==f.sharedfromaid))c[gs("Share")]=
function(){s(a.id)};c[gs("Delete")]=function(){b.lpevent("v_rgtd");b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)})};c[gs("Edit")]=function(){b.lpevent("v_rgte");b.editAid(a.id,window)};"undefined"!=typeof getBG().g_sites[a.id]&&(c[gs("Go to URL")]=function(){b.lpevent("v_g2");b.gotourl(a.id,null)});return[c]},{theme:"vista"}).show(b,c)},100);c.preventDefault()}}var lastqstr="";
function SearchTree(a,b){g_CNTsearch_tree++;var c=!1;0<document.location.href.indexOf("cmd=viewcreditmon")&&1!=g_autoselectcredmontab?(ontabchange(document.getElementById("credmon")),g_autoselectcredmontab=1):"sites"!=g_activetab.id&&(c=!0);var f=$("#q").val(),g=!1;if(a||f!=lastqstr)c&&!b&&(ontabchange(document.getElementById("sites")),g=!0),gLastSearch=lastqstr=f,""==f?clearTree():$.tree.focused().search(f);c&&!g&&setTimeout(function(){ontabchange(g_activetab)},0);document.getElementById("searchxlink").style.visibility=
""==f?"hidden":"visible"}function ls(a){var b=getBG();b.lpevent("v_ls");b.launch(a);return!1}function cu(a){var b=getBG();b.lpevent("v_cu");b.copyusername(a);return!1}function cp(a){var b=getBG();b.lpevent("v_cp");b.copypassword(a);return!1}function curl(a){var b=getBG();b.lpevent("v_curl");b.copyurl(a);return!1}function e(a){var b=getBG();b.lpevent("v_e");b.editAid(a,window);return!1}function d(a){var b=getBG();b.lpevent("v_d");b.deleteAid(a,window);return!1}
function is_protected(a){"string"==typeof a&&(a=a.split(","));for(var b=0;b<a.length;b++){var c=get_record(a[b]);if(c&&1==c.pwprotect)return!0}return!1}function s(a){getBG().lpevent("v_s");callServerFunction("share",a);return!1}function MoveFocus(a){if(40==a.keyCode||34==a.keyCode||38==a.keyCode||33==a.keyCode)a=38==a.keyCode||33==a.keyCode?getgroupidfromname(g_lastnodeid):getgroupidfromname(g_rootnodeid),$.tree.focused().select_branch("#"+a),document.getElementById("q").blur()}
function clearTree(){g_CNTclear_tree++;populate("");document.getElementById("searchxlink").style.visibility="hidden";document.getElementById("q").value=""}var massoperation=!1;function expandall(){if(!getBG().lploggedin)return!1;massoperation=!0;$.tree.focused().open_all();massoperation=!1;saveGroupState()}function collapseall(){if(!getBG().lploggedin)return!1;massoperation=!0;$.tree.focused().close_all();massoperation=!1;saveGroupState()}
function creategroup(){var a=getBG();a.lploggedin&&(a.lpevent("v_cg"),openCreateGroup(null))}
function showformfill(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a=getBG(),b={},c;for(c in a.g_formfills)a.g_formfills.hasOwnProperty(c)&&a.check_ident_ffid(a.g_formfills[c].ffid)&&(b[of(a.g_formfills[c].decprofilename)]=function(a){editff(a.innerText)});a={};a[gs("Add Profile")]=function(){getBG().addprofile()};a[gs("Add Credit Card")]=function(){getBG().addcreditcard()};return[b,"context-menu-separator",a]},{theme:"vista"}).show(a,
b)},0);return!1}function editff(a){var b=getBG();a=$.trim(a);for(var c in b.g_formfills)if(b.g_formfills.hasOwnProperty(c)&&a==$.trim(b.g_formfills[c].decprofilename)){b.editprofile(b.g_formfills[c].ffid);break}}
function showmoremenu(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a={};gHidePreferences||(a[gs("Preferences")]=function(){getBG().openprefs()});getBG().LPISLOC||(a[gs("History")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&openhistory=1")},a[gs("Show Deleted Sites")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&showdeleted=1")});if(!getBG().LPISLOC||!getBG().LPISUPEK)a[gs("Change Password")]=
function(){getBG().unlock_plug2web();getBG().changemasterpassword()};a[gs("Forums")]=function(){getBG().openURL("http://forums.lastpass.com")};a[gs("Blog")]=function(){getBG().openURL("http://blog.lastpass.com")};getBG().g_isadmin&&(a[gs("Admin Tools")]=function(){getBG().openURL("https://rodan.lastpass.com/admintools/")});return[a]},{theme:"vista"}).show(a,b)},0);return!1}function addsecurenote(){getBG().lpevent("v_addn");getBG().openaddsecurenote();return!1}
function logoff(){if(!getBG().lploggedin)return!1;finish_vault_search();getBG().lpevent("v_off");saveGroupState();getBG().loggedOut(!1,"homelocal2");return!1}function accept(a){getBG().lpevent("v_apt");callServerFunction("acceptshare",a)}function reject(a){getBG().lpevent("v_rjt");callServerFunction("rejectshare",a)}function login(){getBG().lpevent("v_lgn");getBG().open_login(!0);return!1}
function changeidentity(a,b){("undefined"==typeof b||!0==b)&&closepopup();getBG();getBG().lpevent("v_cid");getBG().switch_identity(a);document.getElementById("identity").value=getBG().g_identity;setusernametext(getBG().g_username);closepopup()}var addedjqueryui=!1;function addJqueryUI(){if(!addedjqueryui){addedjqueryui=!0;var a=document.createElement("script");a.setAttribute("src",getchromeurl("jquery-ui.min.js"));a.setAttribute("type","text/javascript");document.head.appendChild(a)}}
var gMoveSelected=null;
function openMoveGroup(a,b,c){addedjqueryui||(addJqueryUI(),setTimeout(function(){openMoveGroup(a,b)},250));gMoveSelected=$.tree.focused().selected_arr;if("undefined"==typeof gMoveSelected||0==gMoveSelected.length)gMoveSelected=Array(a);var f=getBG(),g=[],j=[],k=[f.g_sites,f.g_securenotes,f.g_applications],h="",n;for(n in k)if(k.hasOwnProperty(n)){var l=k[n],w;for(w in l)if(l.hasOwnProperty(w)){var u=l[w];if(gMoveSelected&&(1==gMoveSelected.length&&getmoveid(gMoveSelected[0])==get_record_id(u))&&
(h=u.group,b)){""!=u.group&&(g[g.length]=u.group);break}u=""!=u.group?u.group:gs("(none)");"undefined"!=typeof u&&"undefined"==typeof j[u]&&(j[u]="1",g[g.length]=u)}}g.sort(function(a,b){return"_Apps assigned to me"==a?-1:"_Apps assigned to me"==b?1:a.toLowerCase()<b.toLowerCase()?-1:1});j=!1;""==h&&(1==gMoveSelected.length&&!isNumber(getmoveid(gMoveSelected[0])))&&(h=getmoveid(gMoveSelected[0]),j=!0);k=-1!=h.indexOf("\\")&&0<h.substring(h.indexOf("\\")+1).length;if(j&&0===h.indexOf("Shared-")&&!k){if(g=
void 0,c){for(i in f.g_sites)if(f.g_sites[i].group==h){g=f.g_sites[i].aid;break}callServerFunction("renamesharedfolder",g)}}else document.getElementById("grpsel").value="",repopulate_combo("grpsel",g),document.getElementById("dialog").title=gs("Change Group Name"),document.getElementById("dialogtext").innerHTML=gs("Select or enter a new group name"),document.getElementById("dialoggrpinp").style.display="none",document.getElementById("dialoggrpsel").style.display="",document.getElementById("dosubgroup").value=
"undefined"!=typeof b&&b?"1":"0",1==gMoveSelected.length&&(b?document.getElementById("dialogtext").innerHTML+="<br/><br/>"+gs("Group will be created or currently exists under")+": <br/>"+of(h):document.getElementById("grpsel").value=h),$("#dialog").dialog("destroy"),$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,dragStop:function(){var a=document.getElementById("grpsel_combo");a&&"block"==a.style.display&&realShowCombo()},close:function(){var a=document.getElementById("grpsel_combo");
a&&"block"==a.style.display&&close_combo("grpsel")},buttons:{Change:function(){var a=1==gMoveSelected.length?getmoveid(gMoveSelected[0]):"";if(1==gMoveSelected.length&&""!=a&&!is_application(a)&&!isNumber(a))getBG().renameGroup(fix_group(a),fix_group(document.getElementById("grpsel").value));else{for(var b="",c=0;c<gMoveSelected.length;c++)if(a=getmoveid(gMoveSelected[c]),is_application(a)||isNumber(a))b+=(""==b?"":",")+a;if(0==b.length)return;a=document.getElementById("grpsel").value;1==gMoveSelected.length&&
"1"==document.getElementById("dosubgroup").value&&a!=h&&0!=a.indexOf(h+"\\")&&(a=h+"\\"+a);getBG().moveSelectedToGroup(a,b)}populate(gLastSearch);$(this).dialog("close")},Close:function(){$(this).dialog("close")}}}),$("#dialog").dialog("open"),$("#grpsel").click()}var selected_global;
function openCreateGroup(a){addedjqueryui||(addJqueryUI(),setTimeout(function(){openCreateGroup(a)},250));selected_global=a;getBG().lpevent("v_cg");document.getElementById("dialog").title=gs("Group Name");document.getElementById("dialogtext").innerHTML=gs("Group Name");document.getElementById("dialoggrpinp").style.display="";document.getElementById("grpinp").value="";document.getElementById("dialoggrpsel").style.display="none";$("#dialog").dialog("destroy");$("#dialog").dialog({autoOpen:!1,bgiframe:!0,
modal:!0,width:300,minWidth:300,minHeight:250,buttons:{OK:function(){var a=document.getElementById("grpinp").value;for(null!=selected_global&&(a=fix_group(getmoveid(selected_global))+"\\"+a);"\\"==a[0];)a=a.substr(1);if(a==gs("favorites")||a==gs("recently usedlower")||a==gs("(New Pending Share Offers)"))alert(gs("That group already exists."));else if(null==selected_global&&0==a.indexOf("Shared-"))alert(gs("Sorry - group names starting with 'Shared-' are created by LastPass to indicate groups shared with other people. Please use a different name."));
else{var c=getBG(),f=[c.g_sites,c.g_securenotes,c.g_applications],g;for(g in f)if(f.hasOwnProperty(g)){var j=f[g],k;for(k in j)if(j.hasOwnProperty(k)&&j[k].group==a){alert(gs("That group already exists."));return}}c.addEmptyGroup(a);populate(gLastSearch);$(this).dialog("close")}},Close:function(){$(this).dialog("close")}}});$("#dialog").dialog("open");$("#grpinp").click()}
function getmoveid(a){var b="",b="undefined"!=typeof a.id?getgroupnamefromid(a.id,!0):getgroupnamefromid(a.attr("id"),!0);0==b.indexOf("_")&&(b=b.substring(1));return b}function getacct(a){return get_record(a)}
function getDragHTMLForNode(a){var b=a;for(a=0;b&&""==b.attr("id")&&100>a;)b=b.parent(),a++;a=getBG();b=b.attr("id");return(b=getacct(b))?"<div style='background-image:url("+a.geticonurlfromrecord(b)+");background-repeat:no-repeat;'><span style='padding-left: 23px;'>"+of(b.name)+"</span></div>":""}
function getDragHTML(a){var b="<div id='jstree-dragged' class='tree default'>";if(null==a){a=$.tree.focused().selected_arr;for(var c=0;c<a.length;c++)b+=getDragHTMLForNode(a[c])}else b+=getDragHTMLForNode(a);return b+"</div>"}var togglestate=0;
function toggleUserCol(){var a=getcolvisibility("usernamecol"),b=getcolvisibility("ltnamecol"),c="usercol",f="usernamecol",g="usercolhidden",j="usercolvisible",k=a;1==togglestate%2?(c="ltcol",f="ltnamecol",g="ltcolhidden",j="ltcolvisible",k=b):document.getElementById("ltcol").style.paddingRight=!a?"5%":"calc(5% + 20px)";togglestate++;a=document.getElementsByName(c);for(b=0;b<a.length;b++)a[b].className=k?g:j,0==b&&setcolvisibility(f,k?"0":"1")}
function openinparent(a,b){0!=a.indexOf("http")&&(a=g_urlprefix+a);a+="?";for(var c in b)b.hasOwnProperty(c)&&(a+="&"+en(c)+"="+en(b[c]));window.open(a)}function showpopup(){if(getBG().lploggedin){var a=document.getElementById("lppopup"),b=document.getElementById("person");a.style.display="block";a.style.top=parseInt(b.height)+22+"px";a.style.left=b.offsetLeft-180+"px"}else login()}document.addEventListener("click",closepopup,!0);
function closepopup(a){if("block"==document.getElementById("lppopup").style.display&&(!a||!a.target||"person"!=a.target.id&&"identity"!=a.target.id&&"lpusername"!=a.target.id))document.getElementById("lppopup").style.display="none"}var translations=[];translations.DeleteSiteConfirm=gs("Are you sure you want to delete this site?");translations.DeleteSite=gs("Delete Site?");translations.DeleteIdentityConfirm=gs("Are you sure you want to delete this identity?");translations.DeleteIdentity=gs("Delete Identity?");
translations["Invalid Password."]=gs("Invalid Password.");translations["Add Site"]=gs("Add Site");translations["Add Profile"]=gs("Add Profile");translations["Add Identity"]=gs("Add Identity");this.updated_enc=function(){return!0};var g_waitbox=null;
this.show_waitbox=function(a,b){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy());var c=gs("Submitting...");"undefined"!=typeof a&&null!=a&&!0==a?c=gs("LastPass must reencrypt all of your data because of a key change.")+"<br/><br/>"+gs("This may take a while...")+"<br/><br/>"+gs("Please keep this page open until the operation completes.")+'<br/><br/><div id="changepw_progress" style="width: 300px;"></div>':"undefined"!=typeof b&&(b&&""!=b)&&(c=b);b=gs("Please Wait...");var f=Math.min(750,200+4*c.length);
g_waitbox=new Ext.Window({closable:!1,width:f,autoHeight:!0,layout:"fit",modal:!0,title:b,bodyStyle:"padding: 20px",id:"waitbox",html:"<br/><br/><b>"+c+"</b><br/><br/>"});g_waitbox.show()};this.hide_waitbox=function(){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy(),g_waitbox=null)};this.populateff=function(a,b){populateffcommon(convert_object_to_array(getBG().g_formfills),a,b)};this.openff=function(a){getBG().lpevent("v_off");getBG().editprofile(a)};
this.delff=function(a){confirm(gs("Are you sure you would like to delete this form fill profile?"))&&(getBG().lpevent("v_dff"),getBG().deleteformfill(a))};
this.populateident=function(a){var b=convert_object_to_array(getBG().g_identities);if(b.length){if(document.getElementById("identiframe")){var c=document.getElementById("identpane");c.removeChild(document.getElementById("identiframe"))}populateidentcommon(b,a)}else if(!document.getElementById("identiframe")){for(c=document.getElementById("identpane");c.children.length;)c.removeChild(c.children[0]);a=document.createElement("iframe");a.id="identiframe";a.className="overviewiframe";a.src=getpartnerurl("ident_overview.php");
c.appendChild(a)}};this.openident=function(a){getBG().lpevent("v_oid");callServerFunction("identity",a);return!1};this.delident=function(a){getBG().lpevent("v_did");confirm(gs("Are you sure you want to delete this identity?"))&&callServerFunction("deleteidentity",a,getBG().g_token);return!1};
this.populateshares_remote=function(){cleartab("sharepane");var a=document.getElementById("sharepane");if(!document.getElementById("shareiframe")){getBG().unlock_plug2web();var b=document.createElement("iframe");b.id="shareiframe";b.className="overviewiframe";b.src=getpartnerurl("share_overview.php?extension=1");a.appendChild(b)}};
this.populatealerts=function(){cleartab("credmonpane");var a=document.getElementById("credmonpane");if(!document.getElementById("credmoniframe")){var b=document.createElement("iframe");b.id="credmoniframe";b.className="overviewiframe";b.src=getpartnerurl("credmon_overview.php");a.appendChild(b)}};this.cleartab=function(a){for(a=document.getElementById(a);a&&a.children.length;)a.removeChild(a.children[0])};this.refreshsites=function(){getBG().refreshsites()};
this.website_event=function(){var a=document.getElementById("eventtype").value;lpdbg("vault","new vault got website event: "+a);var b={cmd:a,url:g_urlprefix,callback:website_event_callback};switch(a){case "refresh":b.from=document.getElementById("eventdata1").value;b.type=document.getElementById("eventdata2").value;break;case "logoff":break;case "clearcache":break;case "keyweb2plug":b.cmd="web2plug";b.key=document.getElementById("eventdata1").value;b.username=document.getElementById("eventdata2").value;
b.rsa=document.getElementById("eventdata3").value;break;case "checkmultifactorsupport":b.type=document.getElementById("eventdata1").value;break;case "setupsinglefactor":b.type=document.getElementById("eventdata1").value;b.username=document.getElementById("eventdata2").value;b.password=document.getElementById("eventdata3").value;b.silent=document.getElementById("eventdata5").value;"1"!=document.getElementById("eventdata5").value&&g_websiteeventtarget&&g_websiteeventtarget.source.postMessage({cmd:a,
result:"working"},g_websiteeventtarget.origin);break;case "rsadecrypt":b.sharerpublickeyhex=document.getElementById("eventdata1").value;b.sharekeyenchexsig=document.getElementById("eventdata2").value;b.sharekeyenchex=document.getElementById("eventdata3").value;b.sharekeyhex=document.getElementById("eventdata4").value;break;case "request_native_messaging":break;default:console.error("got unsupported website event on new vault: "+a);return}getBG().processCS(null,b,null)};
this.website_event_callback=function(a){lpdbg("vault","new vault got website event callback: "+a.cmd);"checkmultifactorsupport"==a.cmd?(document.getElementById("eventdata4").value=a.type,document.getElementById("eventdata3").value=a.result,g_websiteeventtarget&&g_websiteeventtarget.source.postMessage(a,g_websiteeventtarget.origin)):"setupsinglefactor"==a.cmd?(document.getElementById("eventdata4").value=a.result,g_websiteeventtarget&&g_websiteeventtarget.source.postMessage(a,g_websiteeventtarget.origin)):
"ipcgotdata"==a.cmd&&g_ipctarget.source.postMessage(a,g_ipctarget.origin)};var g_loaded=g_haspluginrsa=!1,g_func=null;this.callFunction=function(a){getBG().lploggedin&&(g_loaded?a():(g_func=a,a=document.createElement("link"),a.rel="stylesheet",a.type="text/css",a.href=g_urlprefix+"m.php/default_ext",document.body.appendChild(getpartnerurl(a)),a=document.createElement("script"),a.src=g_urlprefix+getpartnerurl("m.php/localvault_async?rand="+Math.floor(1E3*Math.random())),document.body.appendChild(a)))};
this.doneloadingexternaljs=function(){g_loaded=!0;g_func&&g_func();g_func=null};this.openaddbytab=function(){if(getBG().lploggedin)return"ident"==g_activetab.id?callServerFunction("identity",""):"ff"==g_activetab.id||"credmon"==g_activetab.id?getBG().addprofile():getBG().openaddsite(),!1};this.opencreditmondash=function(a,b){if(getBG().lploggedin)return a?callServerFunction("opencreditmondash",b):callServerFunction("opencreditmondashnoalert",b),!1};function togglerows(){}
var g_ipctarget=null,g_websiteeventtarget=null;
window.addEventListener("message",function(a){if(0==getBG().base_url.indexOf(a.origin)){var b=a.data+"";if("addprofile"==b||"addidentity"==b)openaddbytab();else if(0<=b.indexOf("showcredmondash_"))a=b.substr(16),opencreditmondash(!0,a);else if(0<=b.indexOf("showcredmondashnoalert_"))a=b.substr(23),opencreditmondash(!1,a);else if("object"==typeof a.data)if("getdata"==a.data.msg)0==a.data.url.indexOf(getBG().base_url)&&(g_ipctarget=a,getBG().processCS(null,{cmd:"ipcgetdata",url:a.data.url,callback:website_event_callback},
null));else if("refreshsites"==a.data.msg)getBG().refreshsites();else if("closeiframe"==a.data.msg)a=document.body,b=document.getElementById("__serveriframe"),a&&b&&a.removeChild(b);else if("websiteevent"==a.data.msg)g_websiteeventtarget=a,document.getElementById("eventtype").value=a.data.eventtype,document.getElementById("eventdata1").value=a.data.eventdata1,document.getElementById("eventdata2").value=a.data.eventdata2,document.getElementById("eventdata3").value=a.data.eventdata3,document.getElementById("eventdata4").value=
a.data.eventdata4,document.getElementById("eventdata5").value=a.data.eventdata5,website_event();else if(0==a.data.msg.indexOf("sharefolder_")&&(b=a.data.msg.match(/^sharefolder_([^_]+)_(.*)$/)))a=b[1],b=b[2],"undefined"!=typeof share_folder_group&&share_folder_group==b&&(share_folder_id=a,getBG().set_share_folder_id(a))}},!1);
function callServerFunction(a,b,c,f){var g=getBG();if(g.lploggedin){g.unlock_plug2web();var j=document,k=!1;if("share"==a||"acceptshare"==a||"rejectshare"==a){if(k=g.g_prompts.edit_site_prompt||g.g_prompts.edit_sn_prompt,!k&&"share"==a)for(var h=b.split(","),n=0;n<h.length;n++){var l=get_record(h[n]);if(l&&l.pwprotect){k=!0;break}}}else if("identity"==a||"deleteidentity"==a){if(k=g.g_prompts.switch_identity_prompt,!k&&""!=b){h=convert_object_to_array(g.g_identities);for(n=0;n<h.length;++n)if(h[n].iid==
b&&h[n].pw_prompt){k=!0;break}}}else if("opencreditmondash"==a||"opencreditmondashnoalert"==a)k=!1;if(k&&!f)g.security_prompt(function(){callServerFunction(a,b,c,!0)});else{f=j.body;j=j.createElement("iframe");j.type="content";g=1E3*Math.random();g=g_urlprefix+"acctsiframe.php?rand="+g+"&command="+encodeURIComponent(a);b&&(g+="&commandid="+encodeURIComponent(b));c&&(g+="&commandtoken="+encodeURIComponent(c));g+="&version="+encodeURIComponent(lpversion);j.setAttribute("src",getpartnerurl(g));j.id=
"__serveriframe";j.style.position="absolute";j.style.top=j.style.left="0px";try{var w=f.ownerDocument.defaultView.getComputedStyle(f,"");j.style.width=w.width;j.style.height=w.height}catch(u){}f.appendChild(j)}}}function manageSharedFolder(a){var b=getBG(),c=a.indexOf("\\");-1!=c&&(a=a.substring(0,c));for(var f in b.g_shares)if(b.g_shares[f].decsharename==a){callServerFunction("sharedfolders",b.g_shares[f].id);break}}
function shareFolder(a){share_folder_id="";getBG().set_share_folder_id("");share_folder_group=a;getBG().set_share_folder_group(a);callServerFunction("sharefolder",a)}
function openGroupMenu(a,b,c,f){var g=getrawgroupid(a.id);setTimeout(function(){$.contextMenu.create(function(){var c=getBG(),f={},h=gs("recently usedlower");b!=gs("favorites")&&(b!=h&&b!=gs("(New Pending Share Offers)"))&&(0==b.indexOf("Shared-")?f[gs("Manage Shared Folder")]=function(){manageSharedFolder(b)}:"1"==getBG().g_enterpriseuser&&!is_personal_linked(b)&&(f[gs("Share Folder")]=function(){shareFolder(b)}),f[gs("Rename Group")]=function(){c.lpevent("v_ren");openMoveGroup(a,void 0,!0)},f[gs("Delete Group")]=
function(){c.lpevent("v_dg");c.deleteGroup(fix_group(b),window,function(){$.tree.focused().cut(a)},"homelocal2.html B",0,g)},f[gs("Create Sub-Group")]=function(){c.lpevent("v_csub");openCreateGroup(a)});f[gs("Open All")]=function(){c.openall(b)};return[f]},{theme:"vista"}).show(c,f)},0)};
