var do_bgiconinput=!0;
function popupfill_create_iframe(a,c,b,e,d,f,g,h){if(do_experimental_popupfill&&a){c=parseInt(c)+"px";b=parseInt(b)+"px";var j=a.body;if(j){a=a.createElement("iframe");a.id=LPMAGICIFRAME+e;a.name=LPMAGICIFRAME+e;g_fixed_iframe_position?h=!0:"undefined"==typeof h&&(h=!1);h&&(g_fixed_shuffled_once=!1);a.src=g_isie?"https://0.lastpass.com/#framesrc=LPMAGIC":urlprefix+"popupfilltab.html";0>parseInt(c)&&(c="0px");0>parseInt(b)&&(b="0px");dotrans?(g_frame_css_str=h?"display:block; position:fixed !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+
" !important; border-style:none !important;":"display:block; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:none !important;","undefined"!=typeof g_isie&&g_isie&&(g_frame_css_str+="background-color:transparent !important;background-image:none !important;")):g_frame_css_str=h?"display:block; position:fixed !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5);":
"display:block; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5);";a.style.cssText=g_frame_css_str;try{j.appendChild(a)}catch(k){verbose_log("append failed! "+
k);return}a.width=parseInt(f)+"px";a.height=g_isie?"38px":"26px";"undefined"!=typeof d&&0<d&&(a.height=24*d+23+"px");a.height=0<parseInt(g)?parseInt(g)+"px":parseInt(a.height)+"px";e=parseInt(a.width)+"px";d=parseInt(a.height)+"px";a.style.cssText=g_frame_css_str+("width: "+e+" !important; height: "+d+" !important; top:"+b+" !important; left:"+c+" !important; ")}}}
function weasel(a){g_ctr_weasel++;if(do_experimental_popupfill){if("undefined"==typeof a||!1==a||!0==a||5>a)a=200;g_weaseled=!0;popupfill_resize();g_weasel_id=setTimeout(function(){weasel(a)},a)}}function issaveall(a){a=a.elements;for(var c=0,b=0,e=0,d=0;d<a.length;d++){var f=a[d].type;"password"==f?b++:"text"==f||"tel"==f||"email"==f?c++:"textarea"==f&&e++}return 1==c&&1==b&&0==e?!1:!0}var POPUP_FIELD_OFFSET=-4;
function calculate_iframe_pos(a,c,b,e){if(!do_experimental_popupfill)return null;"undefined"==typeof e&&(e=!1);if(!a||null==c)return null;var d=c.style.left,f=c.style.top;if(g_double_password_hack||g_double_secret_password_hack||0>parseInt(d)||0>parseInt(f)){var g=a.getElementById(LPMAGICIFRAME+LP_pickFieldName(a,c));if(null!=g)return b=LP_getAbsolutePos(a,g),f=parseInt(b.top)+"px",d=parseInt(b.left)+"px",{posx:d,posy:f}}LP_pickFieldName(a,c);if(null!=c){g=LP_getAbsolutePos(a,c);null!=g&&(d=parseInt(g.left)+
POPUP_FIELD_OFFSET+"px",f=parseInt(g.top)+parseInt(g.height)+"px",g_do_icon_number_hint&&(f=parseInt(g.top)+parseInt(g.height)+4+"px"));if(null==b||0==b||""==b)g=LP_getElementByIdOrName(a,LPMAGICIFRAME+LP_pickFieldName(a,c)),b=null!=g?LP_getAbsolutePos(a,g)?LP_getAbsolutePos(a,g).width:0:0;if(!e){a=LP_getWindowWidth(window);if(!a)return{posx:0,posy:0};parseInt(b)+parseInt(d)>a&&(d=a-parseInt(b)-20+"px")}}if(""==d||"auto"==d||""==f||"auto"==f)return null;b=parseInt(d);f=parseInt(f);return"NaN"==b||
"NaN"==f?null:{posx:b+"px",posy:f+"px"}}function verbose_log(a){verbose&&console_log(a)}function is_watermark(){return!1}function checkAskGenerate(){}function sendKey(a,c){try{return keyName="DOM_VK_"+a.toUpperCase(),send_simulated_key(c,0,KeyEvent[keyName],!1)}catch(b){lpdbg("error",b)}return null}
function send_simulated_key(a,c,b,e){if(void 0===a||void 0===a.ownerDocument)return lpdbg("error","No key target!"),!1;c=a.ownerDocument.createEvent("KeyboardEvent");c.initKeyboardEvent("keydown",!0,!0,document.defaultView,!1,!1,e,!1,b,b);var d=a.dispatchEvent(c);c=a.ownerDocument.createEvent("KeyboardEvent");c.initKeyboardEvent("keyup",!0,!0,null,!1,!1,e,!1,b,b);a.dispatchEvent(c);return d}
if("undefined"==typeof KeyEvent)var KeyEvent={DOM_VK_CANCEL:3,DOM_VK_HELP:6,DOM_VK_BACK_SPACE:8,DOM_VK_TAB:9,DOM_VK_CLEAR:12,DOM_VK_RETURN:13,DOM_VK_ENTER:14,DOM_VK_SHIFT:16,DOM_VK_CONTROL:17,DOM_VK_ALT:18,DOM_VK_PAUSE:19,DOM_VK_CAPS_LOCK:20,DOM_VK_ESCAPE:27,DOM_VK_SPACE:32,DOM_VK_PAGE_UP:33,DOM_VK_PAGE_DOWN:34,DOM_VK_END:35,DOM_VK_HOME:36,DOM_VK_LEFT:37,DOM_VK_UP:38,DOM_VK_RIGHT:39,DOM_VK_DOWN:40,DOM_VK_PRINTSCREEN:44,DOM_VK_INSERT:45,DOM_VK_DELETE:46,DOM_VK_0:48,DOM_VK_1:49,DOM_VK_2:50,DOM_VK_3:51,
DOM_VK_4:52,DOM_VK_5:53,DOM_VK_6:54,DOM_VK_7:55,DOM_VK_8:56,DOM_VK_9:57,DOM_VK_SEMICOLON:59,DOM_VK_EQUALS:61,DOM_VK_A:65,DOM_VK_B:66,DOM_VK_C:67,DOM_VK_D:68,DOM_VK_E:69,DOM_VK_F:70,DOM_VK_G:71,DOM_VK_H:72,DOM_VK_I:73,DOM_VK_J:74,DOM_VK_K:75,DOM_VK_L:76,DOM_VK_M:77,DOM_VK_N:78,DOM_VK_O:79,DOM_VK_P:80,DOM_VK_Q:81,DOM_VK_R:82,DOM_VK_S:83,DOM_VK_T:84,DOM_VK_U:85,DOM_VK_V:86,DOM_VK_W:87,DOM_VK_X:88,DOM_VK_Y:89,DOM_VK_Z:90,DOM_VK_WIN:91,DOM_VK_CONTEXT_MENU:93,DOM_VK_NUMPAD0:96,DOM_VK_NUMPAD1:97,DOM_VK_NUMPAD2:98,
DOM_VK_NUMPAD3:99,DOM_VK_NUMPAD4:100,DOM_VK_NUMPAD5:101,DOM_VK_NUMPAD6:102,DOM_VK_NUMPAD7:103,DOM_VK_NUMPAD8:104,DOM_VK_NUMPAD9:105,DOM_VK_MULTIPLY:106,DOM_VK_ADD:107,DOM_VK_SEPARATOR:108,DOM_VK_SUBTRACT:109,DOM_VK_DECIMAL:110,DOM_VK_DIVIDE:111,DOM_VK_F1:112,DOM_VK_F2:113,DOM_VK_F3:114,DOM_VK_F4:115,DOM_VK_F5:116,DOM_VK_F6:117,DOM_VK_F7:118,DOM_VK_F8:119,DOM_VK_F9:120,DOM_VK_F10:121,DOM_VK_F11:122,DOM_VK_F12:123,DOM_VK_F13:124,DOM_VK_F14:125,DOM_VK_F15:126,DOM_VK_F16:127,DOM_VK_F17:128,DOM_VK_F18:129,
DOM_VK_F19:130,DOM_VK_F20:131,DOM_VK_F21:132,DOM_VK_F22:133,DOM_VK_F23:134,DOM_VK_F24:135,DOM_VK_NUM_LOCK:144,DOM_VK_SCROLL_LOCK:145,DOM_VK_COMMA:188,DOM_VK_PERIOD:190,DOM_VK_SLASH:191,DOM_VK_BACK_QUOTE:192,DOM_VK_OPEN_BRACKET:219,DOM_VK_BACK_SLASH:220,DOM_VK_CLOSE_BRACKET:221,DOM_VK_QUOTE:222,DOM_VK_META:224};var g_formmutations=0;
function checkShouldRecheck(){if(!(20<g_formmutations)&&do_experimental_popupfill&&(verbose_log("entered checkShouldRecheck()"),0<=g_input_cnt&&0<=g_form_cnt)){var a=countInputs(document),c=countFormEquivalents(document);verbose_log("checkShouldRecheck() : # inputs was "+g_input_cnt+", now "+a+" #forms was "+g_form_cnt+" now "+c);if(g_input_cnt!=a||g_form_cnt!=c)g_formmutations++,formcachereset(document),fieldcachereset(document),g_isie?(setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},
200),setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},1E3)):setTimeout(function(){g_ctr_recheck++;evalScriptsInFrame(window,document,!0)},200),g_input_cnt=a,g_form_cnt=c}}function is_watermark_password(){return!1}
function LP_addEventHandler(a,c,b){try{return null==a||null==c||null==b||0>=c.length?null:"undefined"!=typeof a.addEventListener?a.addEventListener(c,b,!1):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,b):null}catch(e){return verbose_log("LP_addEventHandler failed, "+e.message),null}}
function LP_stopEventPropagation(a){try{"undefined"!=typeof a.preventDefault?a.preventDefault():typeof window.event&&(window.event.returnValue=!1),"undefined"!=typeof a.stopPropagation?a.stopPropagation():typeof window.event&&(window.event.cancelBubble=!0)}catch(c){verbose_log("LP_stopEventPropagation failed, "+c.message)}}
function LP_getEventTarget(a){a=a?a:window.event;if((a="undefined"!=typeof a.target?a.target:a.srcElement)&&"undefined"!=typeof a.nodeType&&3==a.nodeType)a=a.parentNode;return a}
function createpopuptoplevel_handler(a){var c=LP_derive_doc(),b=parseInt(a.from_iframe.posx),e=parseInt(a.from_iframe.posy),d=a.from_iframe.id,f=a.from_iframe.rows,g=a.from_iframe.width;a=a.from_iframe.framename;if(!is_your_popup_showing(c)){a=find_iframe_pos(c,a);var h=0,j=0;a?(h=parseInt(a.left)+b+"px",j=parseInt(a.top)+e+"px",g_toplevel_initial_abs_x=h,g_toplevel_initial_abs_y=j):j=h="10px";popupfill_create_iframe(c,h,j,d,f,g,"90px",!0)}}
var g_toplevel_initial_abs_x=null,g_toplevel_initial_abs_y=null;function popupfillresize_handler(a){g_minwidth_override=parseInt(a.width);g_minheight_override=parseInt(a.height);g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&!LP_inIframe(window)&&toplevel_iframe_state_get()&&relocate_popupfill_iframes(document)}
function find_iframe_pos(a,c){if(!a)return null;var b;try{var e=a.getElementsByTagName("IFRAME");if(!c&&1==e.length)return LP_getAbsolutePos(a,e[0]);var d=[];for(b=0;b<e.length;b++)d[b]=e[b];for(b=0;b<d.length;b++)if(d[b].name&&""!=c&&d[b].name==c)return LP_getAbsolutePos(a,d[b])}catch(f){}return null};
