#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

#border
bspc config focused_border_color    red
bspc config border_width        2

#padding and gaps
bspc config top_padding         10
bspc config bottom_padding      8
bspc config left_padding        0
bspc config right_padding       0

bspc config window_gap          8
bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     true


#Misc.
bspc config focus_follows_pointer    true


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
panel &
#xbattbar -a -t 1 bottom -c &
