#! /bin/sh

bspc monitor -d "Work" "Chromium" "Chat" IV V VI VII VIII IX X

# Border
bspc config focused_border_color    red
bspc config border_width            2

# Padding and gaps
bspc config top_padding         10
bspc config bottom_padding      10 
bspc config left_padding        0 
bspc config right_padding       0

bspc config window_gap          0
bspc config split_ratio         0
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config gapless_monicle     true

# Misc.
bspc config focus_follows_pointer   false

# Putting things places
bspc rule -a Chromium desktop=^2 follow=on

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Default things I don't think I want
#bspc config window_gap         12
#bspc config focus_by_distance   true
